// This file is auto-generated by @hey-api/openapi-ts

export type AuditLog = {
    id: string;
    operationType: string;
    targetType: string;
    targetId: string;
    targetName: string;
    content: string;
    operatorId: string;
    operatorName: string;
    operationTime: string;
    details?: {
        [key: string]: string;
    };
    ipAddress: string | null;
    userAgent: string | null;
};

export type Position = {
    positionId: string;
    position_no: string;
    shopId: string | null;
    shop_no: string | null;
    total_space: number;
    put_space: number;
    price_base: number;
    verified: boolean;
    displayed: boolean;
    type: string | null;
    type_tag: string | null;
    photo: Array<string>;
    remark: string | null;
    business_hours: Array<number>;
};

export type SpaceResponseSchema = {
    id: string;
    type: string;
    setting: {
        [key: string]: string;
    };
    count: number;
    state: string;
    /**
     * 价格因子
     */
    price_factor?: number;
    updatedAt: string;
    shopId: string;
    shop?: {
        /**
         * 商标
         */
        trademark?: string;
        /**
         * 门店号
         */
        shop_no?: string;
        branch?: string;
        type_tag?: string;
    };
    /**
     * 分类标签
     */
    tag?: string;
    /**
     * 位置，1-主客区/大堂 2-商家入口 3-入口通道 4-独立房间/包间 5-通往洗手间过道 6-洗手间 7-商家外摆区/店外公共区 8-店外墙面(非临街) 9-店外墙面(临街)
     */
    site?: string;
    /**
     * 稳定性，1-固定 2-半固定 3-移动 4-临时
     */
    stability?: string;
    /**
     * 相册
     */
    photo?: Array<string>;
    /**
     * 投放推介
     */
    description?: string;
    /**
     * 设计注意事项
     */
    design_attention?: string;
    /**
     * 施工注意事项
     */
    construction_attention?: string;
};

export type ShopResponseSchema = {
    shopId: string;
    shop_no?: string;
    trademark: string;
    branch: string | null;
    total_space: number;
    put_space: number;
    price_base: number;
    verified: boolean;
    displayed: boolean;
    type: string;
    type_tag: string | null;
    photo: Array<string>;
    remark: string | null;
    business_hours: Array<number>;
    total_area: number | null;
    customer_area: number | null;
    clerk_count: number | null;
    business_type: string;
    duration: string;
    sex: string;
    age: Array<number>;
    id_tag: string | null;
    sign_photo: string | null;
    contact_type: string;
    /**
     * 商家简介
     */
    shop_description?: string;
    /**
     * 投放简介
     */
    put_description?: string;
    /**
     * 分类标签
     */
    classify_tag?: string;
    positionId?: string;
    position_no?: string;
    /**
     * 休息日，1-周一 2-周二 3-周三 4-周四 5-周五 6-周六 7-周日 8-按需
     */
    rest_days: Array<string>;
    /**
     * 客流高峰，1-早餐 2-午餐 3-晚餐 4-宵夜 5-上午 6-下午 7-晚上 8-深夜
     */
    volume_peak: Array<string>;
    /**
     * 1-春 2-夏 3-秋 4-冬 5-节假日 6-工作日 7-非工作日
     */
    season: Array<string>;
};

export type PartResponseSchema = {
    id: string;
    name: string;
    sequence: number;
    total_space: number;
};

export type DistrictResponseSchema = {
    id: string;
    name: string;
};

export type CityResponseSchema = {
    id: string;
    name: string;
};

export type CbdResponseSchema = {
    id: string;
    name: string;
    addr: string | null;
};

export type PaymentMethod = {
    /**
     * 自动增长的主键
     */
    id: number;
    /**
     * 产品ID
     */
    productId: number;
    /**
     * 平台ID
     */
    platformId: number;
    /**
     * 支付方式类型
     */
    type: string;
    /**
     * 交易类型，例如 wallet、card、bankTransfer 等
     */
    transactionType: string;
    /**
     * 图片链接或资源路径
     */
    imageLink: string;
    /**
     * 收单模式，如 direct、link、checkout 等
     */
    acquiringMode: string;
    /**
     * 处理币种，多个币种以逗号分隔
     */
    processingCurrencies: string;
    /**
     * 产品渠道ID
     */
    productChannelId: number;
    /**
     * 商户ID
     */
    merchantId: number;
    /**
     * 服务提供商ID
     */
    providerId: number;
    /**
     * 平台名称
     */
    platformName: string;
    /**
     * 渠道ID
     */
    channelId: number;
    /**
     * 加价比例（浮点数）
     */
    markup: number;
    /**
     * 保存必要字段的 JSON 字符串
     */
    needField: string;
    /**
     * 保存常规字段的 JSON 字符串
     */
    regular: string;
    /**
     * 支持的消费者国家代码，多个以逗号分隔
     */
    supportedConsumer: string;
    /**
     * 关联的币种信息数组
     */
    currencyInfo: Array<{
        /**
         * 自动增长的主键
         */
        id: number;
        /**
         * 货币的英文名称
         */
        currencyNameEn: string;
        /**
         * 货币的本地名称
         */
        currencyName: string;
        /**
         * ISO 货币代码，例如 USD
         */
        currencyCode: string;
        /**
         * 关联 PaymentMethod 的主键
         */
        paymentMethodId: number;
    }>;
};

export type PaymentMethodListSchema = {
    data: Array<{
        /**
         * 自动增长的主键
         */
        id: number;
        /**
         * 产品ID
         */
        productId: number;
        /**
         * 平台ID
         */
        platformId: number;
        /**
         * 支付方式类型
         */
        type: string;
        /**
         * 交易类型，例如 wallet、card、bankTransfer 等
         */
        transactionType: string;
        /**
         * 图片链接或资源路径
         */
        imageLink: string;
        /**
         * 收单模式，如 direct、link、checkout 等
         */
        acquiringMode: string;
        /**
         * 处理币种，多个币种以逗号分隔
         */
        processingCurrencies: string;
        /**
         * 产品渠道ID
         */
        productChannelId: number;
        /**
         * 商户ID
         */
        merchantId: number;
        /**
         * 服务提供商ID
         */
        providerId: number;
        /**
         * 平台名称
         */
        platformName: string;
        /**
         * 渠道ID
         */
        channelId: number;
        /**
         * 加价比例（浮点数）
         */
        markup: number;
        /**
         * 保存必要字段的 JSON 字符串
         */
        needField: string;
        /**
         * 保存常规字段的 JSON 字符串
         */
        regular: string;
        /**
         * 支持的消费者国家代码，多个以逗号分隔
         */
        supportedConsumer: string;
        /**
         * 关联的币种信息数组
         */
        currencyInfo: Array<{
            /**
             * 自动增长的主键
             */
            id: number;
            /**
             * 货币的英文名称
             */
            currencyNameEn: string;
            /**
             * 货币的本地名称
             */
            currencyName: string;
            /**
             * ISO 货币代码，例如 USD
             */
            currencyCode: string;
            /**
             * 关联 PaymentMethod 的主键
             */
            paymentMethodId: number;
        }>;
    }>;
    code: string;
    msg: string;
    serverTime: number;
    success: boolean;
};

export type OrderStatusSchema = {
    /**
     * 订单状态对象，包含详细的支付信息、订单信息和交易信息
     */
    data: {
        /**
         * 收单模式
         */
        acquiringMode: string;
        /**
         * 买家 ID
         */
        buyerId: string;
        /**
         * 渠道 ID
         */
        channelId: number;
        /**
         * 渠道费率 ID
         */
        channelRatesId: number;
        /**
         * 渠道请求时间 (Unix 时间戳)
         */
        channelRequestTime: number;
        /**
         * 国家代码 (ISO 3166-1 Alpha-2/Alpha-3)
         */
        country: string;
        /**
         * 货币代码 (ISO 4217)
         */
        currency: string;
        /**
         * 预估下游金额
         */
        downstreamEstimatedAmount: number;
        /**
         * 预估下游费用
         */
        downstreamEstimatedFee: number;
        /**
         * 下游费用详情
         */
        downstreamFee: string;
        /**
         * 下游费用 C 版本
         */
        downstreamFeeC: string;
        /**
         * 下游固定费用
         */
        downstreamFixedFee: string;
        /**
         * 下游网关费用
         */
        downstreamGatewayFee: string;
        /**
         * 下游订单号
         */
        downstreamOrderNo: string;
        /**
         * 原始下游订单号
         */
        downstreamOrderNoOrigin: string;
        /**
         * 下游跳转 URL
         */
        downstreamRedirectUrl: string;
        /**
         * 下游交易汇率
         */
        downstreamTxRate: string;
        /**
         * 错误信息
         */
        errorMsg: string;
        /**
         * 预估金额
         */
        estimatedAmount: number;
        /**
         * 预估汇率
         */
        estimatedExchangeRate: string;
        /**
         * 失败原因
         */
        failReason: string;
        /**
         * 冻结类型
         */
        freezeType: number;
        /**
         * 订单 ID
         */
        id: number;
        /**
         * 商户货币代码
         */
        merchantCurrency: string;
        /**
         * 商户 ID
         */
        merchantId: number;
        /**
         * 商户名称
         */
        merchantName: string;
        /**
         * 商户订单金额
         */
        merchantOrderAmount: number;
        /**
         * 商户请求时间 (Unix 时间戳)
         */
        merchantRequestTime: number;
        /**
         * 订单金额
         */
        orderAmount: number;
        /**
         * 订单创建时间 (Unix 时间戳)
         */
        orderCreateTime: number;
        /**
         * 订单状态，例如 PENDING, SUCCESS, FAILED
         */
        orderStatus: string;
        /**
         * 订单类型
         */
        orderType: string;
        /**
         * 订单来源
         */
        origin: string;
        /**
         * 支付兑换金额
         */
        paymentExchange: number;
        /**
         * 支付兑换汇率
         */
        paymentExchangeRate: number;
        /**
         * 支付方式
         */
        paymentMethod: string;
        /**
         * 支付交易加成
         */
        paymentTxMarkup?: number;
        /**
         * 美元支付交易加成
         */
        paymentTxMarkupUsd?: number;
        /**
         * 平台 ID
         */
        platformId: number;
        /**
         * 平台订单号
         */
        platformOrderNo: string;
        /**
         * 产品渠道 ID
         */
        productChannelId: number;
        /**
         * 产品 ID
         */
        productId: number;
        /**
         * 利润
         */
        profit: number;
        /**
         * 供应商 ID
         */
        providerId: number;
        /**
         * 请求状态
         */
        requestStatus: number;
        /**
         * 审核状态
         */
        reviewStatus: string;
        /**
         * 风险类型
         */
        riskType: number;
        /**
         * 会话 ID
         */
        sessionId: string;
        /**
         * 结算货币代码
         */
        settlementCurrency: string;
        /**
         * 结算周期
         */
        settlementCycle: string;
        /**
         * 交易类型
         */
        transactionType: string;
        /**
         * 上游预估金额
         */
        upstreamEstimatedAmount: number;
        /**
         * 上游预估费用
         */
        upstreamEstimatedFee: number;
        /**
         * 上游费用
         */
        upstreamFee: string;
        /**
         * 上游固定费用
         */
        upstreamFixedFee: string;
        /**
         * 上游网关费用
         */
        upstreamGatewayFee: string;
        /**
         * 上游订单号
         */
        upstreamOrderNo: string;
        /**
         * 上游状态
         */
        upstreamStatus: string;
        /**
         * 上游交易汇率
         */
        upstreamTxRate: string;
    };
    code: string;
    msg: string;
    serverTime: number;
    success: boolean;
};

export type AllInOneOutputSchema = {
    /**
     * 完整的 API 响应数据，包含支付操作、订单信息、客户信息等
     */
    data: {
        /**
         * 支付操作相关信息
         */
        action?: {
            paymentMethodType: 'alipay' | 'americanexpress' | 'applepay' | 'applepayus' | 'bancomatpay' | 'blikoneclick' | 'blik' | 'bitpay' | 'cashapppay' | 'duitnow' | 'eps' | 'fpxonlinebanking' | 'fpx' | 'finlandbanks' | 'giropay' | 'gopay' | 'googlepay' | 'googlepayus' | 'indonesiabanks' | 'jcb' | 'konbini' | 'koreandomesticcards' | 'mbbank' | 'mastercard' | 'mybank' | 'oxxo' | 'pix' | 'payeasy' | 'paypal' | 'payconiq' | 'paysafecard' | 'p24' | 'przelewy24' | 'przelewy24p24' | 'satispay' | 'sepadebit' | 'sepaddmodelc' | 'sepaddmodela' | 'skrill' | 'todito' | 'tosspay' | 'touchngo' | 'trustly' | 'upi' | 'unionpay' | 'visa' | 'wechatpay' | 'zip' | 'zipus' | 'pbba' | 'paybybankapp' | 'paybybankapppbba' | 'payu' | 'klasha' | 'card' | 'banktransaction' | 'mobilemoney' | 'mpesa' | 'wemabank' | 'cardafrica' | 'afterpay' | 'klarna' | 'payovertimeklarna' | 'paylaterklarna' | 'paynowklarna' | 'banktransferklarna' | 'directdebitklarna' | 'upiinstore' | 'mbway' | 'thaibanks' | 'thaibanksapp' | 'skrilltap' | 'clearpay' | 'onlinebanking' | 'doku' | 'shoppepay' | 'shopeepay' | 'truemoney' | 'kbank' | 'kodd' | 'thaiqr' | 'cardus' | 'cardsus' | 'kakaopay' | 'tmn' | 'mpay' | 'rabbitlinepay' | 'boost' | 'bpi' | 'tng' | 'dana' | 'alipayhk' | 'gcash' | 'tsp' | 'tinaba' | 'kredivo' | 'naverpay' | 'kplus' | 'billease' | 'alipaycn' | 'creditcardupop' | 'alipayup' | 'upop' | 'wechatpayup' | 'qp' | 'creditcardvm';
            /**
             * 支付页面 URL
             */
            url: string;
            /**
             * 应用程序跳转链接
             */
            applinkUrl?: string;
            /**
             * Scheme URL
             */
            schemeUrl?: string;
            /**
             * 支付 URL
             */
            payUrl?: string;
            /**
             * HTTP 方法，例如 GET, POST
             */
            method: string;
            /**
             * 支付操作类型，可选值：redirect、pin、avs、sms、qrcode
             */
            type: 'redirect' | 'pin' | 'avs' | 'sms' | 'qrcode';
            /**
             * 支付二维码内容
             */
            qrCode: string;
            /**
             * 支付提示信息
             */
            message?: string;
            /**
             * 需要填写的支付字段列表
             */
            fields?: Array<string>;
        };
        /**
         * 订单金额信息
         */
        amount?: {
            /**
             * 货币类型，ISO 4217 三位字母代码
             */
            currency: string;
            /**
             * 金额的最小单位值，例如分、厘
             */
            value: number;
        };
        /**
         * 订单信息
         */
        order?: {
            /**
             * 付款账户唯一标识
             */
            account: string;
            /**
             * 订单金额信息
             */
            amount: {
                /**
                 * 货币类型，ISO 4217 三位字母代码
                 */
                currency: string;
                /**
                 * 金额的最小单位值，例如分、厘
                 */
                value: number;
            };
            /**
             * 账户持有人姓名
             */
            accountName: string;
            /**
             * 银行名称
             */
            bank: string;
            /**
             * 订单过期时间（ISO 8601 格式）
             */
            expiresAt: Date;
            /**
             * 订单备注信息
             */
            note: string;
        };
        /**
         * 客户信息
         */
        customer?: {
            /**
             * 客户唯一 ID
             */
            id: string;
            /**
             * 客户电话号码，符合 E.164 格式
             */
            phone: string;
            /**
             * 客户姓名
             */
            name: string;
            /**
             * 客户电子邮件地址
             */
            email: string;
            /**
             * 客户创建时间（ISO 8601 格式）
             */
            createdAt: Date;
        };
        /**
         * 拒绝原因或错误信息，若交易失败则提供详细信息
         */
        refusalReason: string;
        /**
         * 支付服务提供商的唯一交易参考号
         */
        pspReference: string;
        /**
         * 商户的订单参考号
         */
        reference?: string;
        /**
         * 交易结果代码，例如 SUCCESS, FAILED, PENDING
         */
        resultCode: string;
    };
    code: string;
    msg: string;
    serverTime: number;
    success: boolean;
};

export type ReferenceInputSchema = {
    /**
     * 订单号
     */
    reference: string;
};

export type TokenInputSchema = {
    token: string;
};

/**
 * 订单金额信息
 */
export type AmountSchema = {
    /**
     * 货币类型，ISO 4217 三位字母代码
     */
    currency: string;
    /**
     * 订单金额，单位为最小货币单位，例如分、厘
     */
    value: number;
};

export type PaymentHeaderSchema = {
    /**
     * 支付渠道 ID
     */
    providerId: string;
    /**
     * 商户 ID
     */
    merchantId: string;
    /**
     * 应用 ID
     */
    appId: string;
};

/**
 * 支付请求数据结构
 */
export type PaymentInputSchema = {
    /**
     * 订单金额信息
     */
    amount: {
        /**
         * 货币类型，ISO 4217 三位字母代码
         */
        currency: string;
        /**
         * 订单金额，单位为最小货币单位，例如分、厘
         */
        value: number;
    };
    /**
     * 国家代码，符合 ISO 3166-1 Alpha-2 标准
     */
    countryCode: string;
    /**
     * 是否进行汇率转换
     */
    isExchange: boolean;
    /**
     * 商户账户名称
     */
    merchantAccount: string;
    /**
     * 商户 ID
     */
    merchantId: string;
    /**
     * 请求来源，例如 xyz.com
     */
    origin: string;
    paymentMethod: {
        type: 'alipay' | 'americanexpress' | 'applepay' | 'applepayus' | 'bancomatpay' | 'blikoneclick' | 'blik' | 'bitpay' | 'cashapppay' | 'duitnow' | 'eps' | 'fpxonlinebanking' | 'fpx' | 'finlandbanks' | 'giropay' | 'gopay' | 'googlepay' | 'googlepayus' | 'indonesiabanks' | 'jcb' | 'konbini' | 'koreandomesticcards' | 'mbbank' | 'mastercard' | 'mybank' | 'oxxo' | 'pix' | 'payeasy' | 'paypal' | 'payconiq' | 'paysafecard' | 'p24' | 'przelewy24' | 'przelewy24p24' | 'satispay' | 'sepadebit' | 'sepaddmodelc' | 'sepaddmodela' | 'skrill' | 'todito' | 'tosspay' | 'touchngo' | 'trustly' | 'upi' | 'unionpay' | 'visa' | 'wechatpay' | 'zip' | 'zipus' | 'pbba' | 'paybybankapp' | 'paybybankapppbba' | 'payu' | 'klasha' | 'card' | 'banktransaction' | 'mobilemoney' | 'mpesa' | 'wemabank' | 'cardafrica' | 'afterpay' | 'klarna' | 'payovertimeklarna' | 'paylaterklarna' | 'paynowklarna' | 'banktransferklarna' | 'directdebitklarna' | 'upiinstore' | 'mbway' | 'thaibanks' | 'thaibanksapp' | 'skrilltap' | 'clearpay' | 'onlinebanking' | 'doku' | 'shoppepay' | 'shopeepay' | 'truemoney' | 'kbank' | 'kodd' | 'thaiqr' | 'cardus' | 'cardsus' | 'kakaopay' | 'tmn' | 'mpay' | 'rabbitlinepay' | 'boost' | 'bpi' | 'tng' | 'dana' | 'alipayhk' | 'gcash' | 'tsp' | 'tinaba' | 'kredivo' | 'naverpay' | 'kplus' | 'billease' | 'alipaycn' | 'creditcardupop' | 'alipayup' | 'upop' | 'wechatpayup' | 'qp' | 'creditcardvm';
        holderName?: string;
        firstName?: string;
        lastName?: string;
        shopperEmail?: string;
    };
    /**
     * 产品详细描述信息
     */
    productDetail: string;
    /**
     * 产品 ID
     */
    productId: string;
    /**
     * 产品名称
     */
    productName: string;
    /**
     * 订单唯一参考号
     */
    reference: string;
    /**
     * 支付完成后的回调 URL
     */
    returnUrl: string;
    /**
     * 支付通知 Webhook URL
     */
    webhookUrl: string;
    /**
     * 浏览器终端信息
     */
    browserInfo?: {
        /**
         * 终端类型，例如 WEB, MOBILE
         */
        terminalType?: string;
    };
    /**
     * 支付处理货币，符合 ISO 4217 货币代码
     */
    processingCurrency: string;
};

export type PaymentOrderOutputSchemaFastify = {
    countryCode: string;
    productId: string;
    merchantId: string;
    origin: string;
    productName: string;
    productDetail: string;
    pspReference?: string | unknown;
    reference: string;
    returnUrl: string;
    merchantAccount?: string | unknown;
    webhookUrl?: string | unknown;
    PaymentMethod?: string;
    version: number;
    isexchange: boolean;
    amount: {
        currency: string;
        value: number;
    };
    expiredAt: Date;
};

export type PaymentOrderDebugSchema = {
    /**
     * 支付金额（整数，实际金额乘以 100，例如 200 USD 传入 20000）
     */
    amount: number;
    /**
     * 货币代码（3 个大写字母，例如 USD）
     */
    currency: string;
    /**
     * 持卡人姓名
     */
    holderName?: string;
    /**
     * 购物者邮箱
     */
    shopperEmail?: string;
    /**
     * 支付方式（例如 alipaycn）
     */
    paymentType?: string;
    /**
     * 商户 ID
     */
    merchantId?: string;
};

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetResponses = {
    /**
     * Default Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetResponse = GetResponses[keyof GetResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Default Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetApiHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetApiHealthResponses = {
    /**
     * Default Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetApiHealthResponse = GetApiHealthResponses[keyof GetApiHealthResponses];

export type GetCityCityListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/city/cityList';
};

export type GetCityCityListResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            list: Array<{
                id: string;
                name: string;
            }>;
        };
    };
};

export type GetCityCityListResponse = GetCityCityListResponses[keyof GetCityCityListResponses];

export type PostDistrictListData = {
    body?: {
        /**
         * 城市ID
         */
        parentId: string;
    };
    path?: never;
    query?: never;
    url: '/district/list';
};

export type PostDistrictListResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            list: Array<{
                id: string;
                name: string;
            }>;
        };
    };
};

export type PostDistrictListResponse = PostDistrictListResponses[keyof PostDistrictListResponses];

export type PostCbdListData = {
    body?: {
        /**
         * 行政区划ID
         */
        districtId: string;
    };
    path?: never;
    query?: never;
    url: '/cbd/list';
};

export type PostCbdListResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            list: Array<{
                id: string;
                name: string;
                addr: string | null;
            }>;
        };
    };
};

export type PostCbdListResponse = PostCbdListResponses[keyof PostCbdListResponses];

export type PostPartListData = {
    body?: {
        /**
         * 商圈ID
         */
        cbdId?: string;
    };
    path?: never;
    query?: never;
    url: '/part/list';
};

export type PostPartListResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            list: Array<{
                id: string;
                name: string;
                sequence: number;
                total_space: number;
            }>;
        };
    };
};

export type PostPartListResponse = PostPartListResponses[keyof PostPartListResponses];

export type GetPartByIdData = {
    body?: never;
    path: {
        /**
         * 分区ID
         */
        id: string;
    };
    query?: never;
    url: '/part/{id}';
};

export type GetPartByIdResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            id: string;
            name: string;
            sequence: number;
            total_space: number;
        };
    };
};

export type GetPartByIdResponse = GetPartByIdResponses[keyof GetPartByIdResponses];

export type PostPartAddData = {
    body?: {
        /**
         * 商圈ID
         */
        cbdId: string;
        /**
         * 分区名称
         */
        name: string;
        /**
         * 排序值
         */
        sequence: number;
    };
    path?: never;
    query?: never;
    url: '/part/add';
};

export type PostPartAddResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: string;
    };
};

export type PostPartAddResponse = PostPartAddResponses[keyof PostPartAddResponses];

export type PostPartUpdateData = {
    body?: {
        /**
         * 分区ID
         */
        id: string;
        /**
         * 分区名称
         */
        name: string;
    };
    path?: never;
    query?: never;
    url: '/part/update';
};

export type PostPartUpdateResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: string;
    };
};

export type PostPartUpdateResponse = PostPartUpdateResponses[keyof PostPartUpdateResponses];

export type PostPartDeleteData = {
    body?: {
        /**
         * 分区ID
         */
        id: string;
    };
    path?: never;
    query?: never;
    url: '/part/delete';
};

export type PostPartDeleteResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: string;
    };
};

export type PostPartDeleteResponse = PostPartDeleteResponses[keyof PostPartDeleteResponses];

export type PostPositionListData = {
    body?: {
        /**
         * 分区ID
         */
        partId?: string;
    };
    path?: never;
    query?: never;
    url: '/position/list';
};

export type PostPositionListResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            list: Array<{
                positionId: string;
                position_no: string;
                shopId: string | null;
                shop_no: string | null;
                total_space: number;
                put_space: number;
                price_base: number;
                verified: boolean;
                displayed: boolean;
                type: string | null;
                type_tag: string | null;
                photo: Array<string>;
                remark: string | null;
                business_hours: Array<number>;
            }>;
        };
    };
};

export type PostPositionListResponse = PostPositionListResponses[keyof PostPositionListResponses];

export type GetPositionByIdData = {
    body?: never;
    path: {
        /**
         * 铺位ID
         */
        id: string;
    };
    query?: never;
    url: '/position/{id}';
};

export type GetPositionByIdResponses = {
    /**
     * 成功响应
     */
    201: {
        code?: number;
        data?: {
            positionId: string;
            position_no: string;
            shopId: unknown | null;
            shop_no: unknown | null;
            total_space: number;
            put_space: number;
            price_base: number;
            verified: boolean;
            displayed: boolean;
            type: unknown | null;
            type_tag: string | null;
            photo: Array<string>;
            remark: string | null;
            business_hours: Array<number>;
        };
    };
};

export type GetPositionByIdResponse = GetPositionByIdResponses[keyof GetPositionByIdResponses];

export type PostPositionAddData = {
    body?: {
        /**
         * 商圈ID
         */
        cbdId: string;
        /**
         * 分区ID
         */
        partId: string;
        /**
         * 铺位编号
         */
        no: string;
    };
    path?: never;
    query?: never;
    url: '/position/add';
};

export type PostPositionAddResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: string;
    };
};

export type PostPositionAddResponse = PostPositionAddResponses[keyof PostPositionAddResponses];

export type PostPositionUpdateData = {
    body?: {
        /**
         * 铺位ID
         */
        id: string;
        /**
         * 铺位编号
         */
        no: string;
    };
    path?: never;
    query?: never;
    url: '/position/update';
};

export type PostPositionUpdateResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: string;
    };
};

export type PostPositionUpdateResponse = PostPositionUpdateResponses[keyof PostPositionUpdateResponses];

export type PostPositionDeleteData = {
    body?: {
        /**
         * 铺位ID
         */
        id: string;
    };
    path?: never;
    query?: never;
    url: '/position/delete';
};

export type PostPositionDeleteResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: string;
    };
};

export type PostPositionDeleteResponse = PostPositionDeleteResponses[keyof PostPositionDeleteResponses];

export type PostPositionSetData = {
    body?: {
        /**
         * 铺位ID
         */
        id: string;
    };
    path?: never;
    query?: never;
    url: '/position/set';
};

export type PostPositionSetResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: string;
    };
};

export type PostPositionSetResponse = PostPositionSetResponses[keyof PostPositionSetResponses];

export type PostPositionBindShopData = {
    body?: {
        /**
         * 铺位ID
         */
        id: string;
        /**
         * 商家ID
         */
        shopId: string;
    };
    path?: never;
    query?: never;
    url: '/position/bindShop';
};

export type PostPositionBindShopResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: string;
    };
};

export type PostPositionBindShopResponse = PostPositionBindShopResponses[keyof PostPositionBindShopResponses];

export type PostPositionMarkData = {
    body?: {
        /**
         * 铺位ID
         */
        id: string;
        /**
         * 标记内容
         */
        remark: string;
    };
    path?: never;
    query?: never;
    url: '/position/mark';
};

export type PostPositionMarkResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: string;
    };
};

export type PostPositionMarkResponse = PostPositionMarkResponses[keyof PostPositionMarkResponses];

export type GetShopListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/shop/list';
};

export type GetShopListResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            list: Array<{
                shopId: string;
                shop_no?: string;
                trademark: string;
                branch: string | null;
                total_space: number;
                put_space: number;
                price_base: number;
                verified: boolean;
                displayed: boolean;
                type: string;
                type_tag: string | null;
                photo: Array<string>;
                remark: string | null;
                business_hours: Array<number>;
                total_area: number | null;
                customer_area: number | null;
                clerk_count: number | null;
                business_type: string;
                duration: string;
                sex: string;
                age: Array<number>;
                id_tag: string | null;
                sign_photo: string | null;
                contact_type: string;
                /**
                 * 商家简介
                 */
                shop_description?: string;
                /**
                 * 投放简介
                 */
                put_description?: string;
                /**
                 * 分类标签
                 */
                classify_tag?: string;
            }>;
        };
    };
};

export type GetShopListResponse = GetShopListResponses[keyof GetShopListResponses];

export type GetShopListUnbindData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/shop/listUnbind';
};

export type GetShopListUnbindResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            list: Array<{
                shopId: string;
                shop_no?: string;
                trademark: string;
                branch: string | null;
                total_space: number;
                put_space: number;
                price_base: number;
                verified: boolean;
                displayed: boolean;
                type: string;
                type_tag: string | null;
                photo: Array<string>;
                remark: string | null;
                business_hours: Array<number>;
                total_area: number | null;
                customer_area: number | null;
                clerk_count: number | null;
                business_type: string;
                duration: string;
                sex: string;
                age: Array<number>;
                id_tag: string | null;
                sign_photo: string | null;
                contact_type: string;
                /**
                 * 商家简介
                 */
                shop_description?: string;
                /**
                 * 投放简介
                 */
                put_description?: string;
                /**
                 * 分类标签
                 */
                classify_tag?: string;
            }>;
        };
    };
};

export type GetShopListUnbindResponse = GetShopListUnbindResponses[keyof GetShopListUnbindResponses];

export type GetShopByIdData = {
    body?: never;
    path: {
        /**
         * 商家ID
         */
        id: string;
    };
    query?: never;
    url: '/shop/{id}';
};

export type GetShopByIdResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            shopId: string;
            shop_no?: string;
            trademark: string;
            branch: string | null;
            total_space: number;
            put_space: number;
            price_base: number;
            verified: boolean;
            displayed: boolean;
            type: string;
            type_tag: string | null;
            photo: Array<string>;
            remark: string | null;
            business_hours: Array<number>;
            total_area: number | null;
            customer_area: number | null;
            clerk_count: number | null;
            business_type: string;
            duration: string;
            sex: string;
            age: Array<number>;
            id_tag: string | null;
            sign_photo: string | null;
            contact_type: string;
            /**
             * 商家简介
             */
            shop_description?: string;
            /**
             * 投放简介
             */
            put_description?: string;
            /**
             * 分类标签
             */
            classify_tag?: string;
        };
    };
};

export type GetShopByIdResponse = GetShopByIdResponses[keyof GetShopByIdResponses];

export type PostShopAddData = {
    body?: {
        /**
         * 商圈ID
         */
        cbdId: string;
        /**
         * 分区ID
         */
        partId: string;
        /**
         * 铺位ID
         */
        positionId?: string;
        /**
         * 类型，1-餐饮 2-轻食 3-茶楼 4-茶饮/咖啡 5-咖啡馆 6-酒店
         */
        type: string;
        /**
         * 品类标签
         */
        type_tag?: string;
        /**
         * 商业类型，1-独立自营店 2-连锁自营店 3-连锁加盟店
         */
        business_type: string;
        /**
         * 字号
         */
        trademark: string;
        /**
         * 分店
         */
        branch?: string;
        /**
         * 坐标，经纬度
         */
        location: [
            number,
            number
        ];
        /**
         * 是否认证
         */
        verified?: boolean;
        /**
         * 经营时长，1-一年内新店 2-1~2年 3-2~5年 4-五年以上
         */
        duration: string;
        /**
         * 是否展示消费数据
         */
        consume_display?: boolean;
        /**
         * 人均消费最低到最高值，单位(分)
         */
        average_expense: [
            number,
            number
        ];
        /**
         * 性别，1-不限 2-男 3-女
         */
        sex: string;
        /**
         * 年龄段最低到最高值
         */
        age: [
            number,
            number
        ];
        /**
         * 身份标签
         */
        id_tag?: string;
        /**
         * 标识图片
         */
        sign_photo?: string;
        /**
         * 认证图片
         */
        verify_photo?: Array<string>;
        /**
         * 外景图片
         */
        environment_photo?: Array<string>;
        /**
         * 内景图片
         */
        building_photo?: Array<string>;
        /**
         * 品牌营销图片
         */
        brand_photo?: Array<string>;
        /**
         * 联系人姓名
         */
        contact_name?: string;
        /**
         * 联系人电话
         */
        contact_phone?: string;
        /**
         * 联系人类型，1-老板 2-店长 3-店员 4-总店管理人员
         */
        contact_type?: string;
        /**
         * 面积，单位(平方米)
         */
        total_area?: number;
        /**
         * 客区面积
         */
        customer_area?: number;
        /**
         * 店员人数
         */
        clerk_count?: number;
        /**
         * 营业时间
         */
        business_hours: [
            number,
            number
        ];
        /**
         * 休息日，1-周一 2-周二 3-周三 4-周四 5-周五 6-周六 7-周日 8-按需
         */
        rest_days: Array<string>;
        /**
         * 客流高峰，1-早餐 2-午餐 3-晚餐 4-宵夜 5-上午 6-下午 7-晚上 8-深夜
         */
        volume_peak: Array<string>;
        /**
         * 1-春 2-夏 3-秋 4-冬 5-节假日 6-工作日 7-非工作日
         */
        season: Array<string>;
        /**
         * 商家简介
         */
        shop_description?: string;
        /**
         * 投放简介
         */
        put_description?: string;
        /**
         * 是否开放
         */
        displayed?: boolean;
        /**
         * 价格基数（单位：分）
         */
        price_base: number;
        /**
         * 分类标签
         */
        classify_tag?: string;
        /**
         * 备注
         */
        remark?: string;
    };
    path?: never;
    query?: never;
    url: '/shop/add';
};

export type PostShopAddResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            /**
             * 新建商家ID
             */
            id: string;
        };
    };
};

export type PostShopAddResponse = PostShopAddResponses[keyof PostShopAddResponses];

export type PostShopUpdateData = {
    body?: {
        /**
         * 类型，1-餐饮 2-轻食 3-茶楼 4-茶饮/咖啡 5-咖啡馆 6-酒店
         */
        type: string;
        /**
         * 品类标签
         */
        type_tag?: string;
        /**
         * 商业类型，1-独立自营店 2-连锁自营店 3-连锁加盟店
         */
        business_type: string;
        /**
         * 字号
         */
        trademark: string;
        /**
         * 分店
         */
        branch?: string;
        /**
         * 坐标，经纬度
         */
        location: [
            number,
            number
        ];
        /**
         * 是否认证
         */
        verified?: boolean;
        /**
         * 经营时长，1-一年内新店 2-1~2年 3-2~5年 4-五年以上
         */
        duration: string;
        /**
         * 是否展示消费数据
         */
        consume_display?: boolean;
        /**
         * 人均消费最低到最高值，单位(分)
         */
        average_expense: [
            number,
            number
        ];
        /**
         * 性别，1-不限 2-男 3-女
         */
        sex: string;
        /**
         * 年龄段最低到最高值
         */
        age: [
            number,
            number
        ];
        /**
         * 身份标签
         */
        id_tag?: string;
        /**
         * 标识图片
         */
        sign_photo?: string;
        /**
         * 认证图片
         */
        verify_photo?: Array<string>;
        /**
         * 外景图片
         */
        environment_photo?: Array<string>;
        /**
         * 内景图片
         */
        building_photo?: Array<string>;
        /**
         * 品牌营销图片
         */
        brand_photo?: Array<string>;
        /**
         * 联系人姓名
         */
        contact_name?: string;
        /**
         * 联系人电话
         */
        contact_phone?: string;
        /**
         * 联系人类型，1-老板 2-店长 3-店员 4-总店管理人员
         */
        contact_type?: string;
        /**
         * 面积，单位(平方米)
         */
        total_area?: number;
        /**
         * 客区面积
         */
        customer_area?: number;
        /**
         * 店员人数
         */
        clerk_count?: number;
        /**
         * 营业时间
         */
        business_hours: [
            number,
            number
        ];
        /**
         * 休息日，1-周一 2-周二 3-周三 4-周四 5-周五 6-周六 7-周日 8-按需
         */
        rest_days: Array<string>;
        /**
         * 客流高峰，1-早餐 2-午餐 3-晚餐 4-宵夜 5-上午 6-下午 7-晚上 8-深夜
         */
        volume_peak: Array<string>;
        /**
         * 1-春 2-夏 3-秋 4-冬 5-节假日 6-工作日 7-非工作日
         */
        season: Array<string>;
        /**
         * 商家简介
         */
        shop_description?: string;
        /**
         * 投放简介
         */
        put_description?: string;
        /**
         * 是否开放
         */
        displayed?: boolean;
        /**
         * 价格基数（单位：分）
         */
        price_base: number;
        /**
         * 分类标签
         */
        classify_tag?: string;
        /**
         * 备注
         */
        remark?: string;
        /**
         * 商家ID
         */
        id: string;
    };
    path?: never;
    query?: never;
    url: '/shop/update';
};

export type PostShopUpdateResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: string;
    };
};

export type PostShopUpdateResponse = PostShopUpdateResponses[keyof PostShopUpdateResponses];

export type PostShopDeleteData = {
    body?: {
        /**
         * 商家ID
         */
        id: string;
    };
    path?: never;
    query?: never;
    url: '/shop/delete';
};

export type PostShopDeleteResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: string;
    };
};

export type PostShopDeleteResponse = PostShopDeleteResponses[keyof PostShopDeleteResponses];

export type PostSpaceListData = {
    body?: {
        /**
         * 商家ID
         */
        shopId: string;
    };
    path?: never;
    query?: never;
    url: '/space/list';
};

export type PostSpaceListResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            list: Array<{
                id: string;
                type: string;
                setting: {
                    [key: string]: string;
                };
                count: number;
                state: string;
                /**
                 * 价格因子
                 */
                price_factor?: number;
                updatedAt: string;
                shopId: string;
                shop?: {
                    /**
                     * 商标
                     */
                    trademark?: string;
                    /**
                     * 门店号
                     */
                    shop_no?: string;
                    branch?: string;
                    type_tag?: string;
                };
                /**
                 * 分类标签
                 */
                tag?: string;
                /**
                 * 位置，1-主客区/大堂 2-商家入口 3-入口通道 4-独立房间/包间 5-通往洗手间过道 6-洗手间 7-商家外摆区/店外公共区 8-店外墙面(非临街) 9-店外墙面(临街)
                 */
                site?: string;
                /**
                 * 稳定性，1-固定 2-半固定 3-移动 4-临时
                 */
                stability?: string;
                /**
                 * 相册
                 */
                photo?: Array<string>;
                /**
                 * 投放推介
                 */
                description?: string;
                /**
                 * 设计注意事项
                 */
                design_attention?: string;
                /**
                 * 施工注意事项
                 */
                construction_attention?: string;
            }>;
        };
    };
};

export type PostSpaceListResponse = PostSpaceListResponses[keyof PostSpaceListResponses];

export type GetSpaceByIdData = {
    body?: never;
    path: {
        /**
         * 广告位ID
         */
        id: string;
    };
    query?: never;
    url: '/space/{id}';
};

export type GetSpaceByIdResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            id: string;
            type: string;
            setting: {
                [key: string]: string;
            };
            count: number;
            state: string;
            /**
             * 价格因子
             */
            price_factor?: number;
            updatedAt: string;
            shopId: string;
            shop?: {
                /**
                 * 商标
                 */
                trademark?: string;
                /**
                 * 门店号
                 */
                shop_no?: string;
                branch?: string;
                type_tag?: string;
            };
            /**
             * 分类标签
             */
            tag?: string;
            /**
             * 位置，1-主客区/大堂 2-商家入口 3-入口通道 4-独立房间/包间 5-通往洗手间过道 6-洗手间 7-商家外摆区/店外公共区 8-店外墙面(非临街) 9-店外墙面(临街)
             */
            site?: string;
            /**
             * 稳定性，1-固定 2-半固定 3-移动 4-临时
             */
            stability?: string;
            /**
             * 相册
             */
            photo?: Array<string>;
            /**
             * 投放推介
             */
            description?: string;
            /**
             * 设计注意事项
             */
            design_attention?: string;
            /**
             * 施工注意事项
             */
            construction_attention?: string;
        };
    };
};

export type GetSpaceByIdResponse = GetSpaceByIdResponses[keyof GetSpaceByIdResponses];

export type PostSpaceAddData = {
    body?: {
        /**
         * 商家ID
         */
        shopId: string;
        /**
         * 广告位类型，1-方桌不干胶贴 2-方桌餐垫纸 3-立牌 4-X展架 5-电视/LED屏幕 6-投影仪
         */
        type: string;
        /**
         * 广告位设置
         */
        setting: {
            [key: string]: string;
        };
        /**
         * 广告位数量
         */
        count?: number;
        /**
         * 状态 1-启用 2-禁用
         */
        state: string;
        /**
         * 价格因子
         */
        price_factor?: number;
        /**
         * 分类标签
         */
        tag?: string;
        /**
         * 位置，1-主客区/大堂 2-商家入口 3-入口通道 4-独立房间/包间 5-通往洗手间过道 6-洗手间 7-商家外摆区/店外公共区 8-店外墙面(非临街) 9-店外墙面(临街)
         */
        site?: string;
        /**
         * 稳定性，1-固定 2-半固定 3-移动 4-临时
         */
        stability?: string;
        /**
         * 相册
         */
        photo?: Array<string>;
        /**
         * 投放推介
         */
        description?: string;
        /**
         * 设计注意事项
         */
        design_attention?: string;
        /**
         * 施工注意事项
         */
        construction_attention?: string;
    };
    path?: never;
    query?: never;
    url: '/space/add';
};

export type PostSpaceAddResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: string;
    };
};

export type PostSpaceAddResponse = PostSpaceAddResponses[keyof PostSpaceAddResponses];

export type PostSpaceUpdateData = {
    body?: {
        /**
         * 广告位类型，1-方桌不干胶贴 2-方桌餐垫纸 3-立牌 4-X展架 5-电视/LED屏幕 6-投影仪
         */
        type: string;
        /**
         * 广告位设置
         */
        setting: {
            [key: string]: string;
        };
        /**
         * 广告位数量
         */
        count?: number;
        /**
         * 状态 1-启用 2-禁用
         */
        state: string;
        /**
         * 价格因子
         */
        price_factor?: number;
        /**
         * 分类标签
         */
        tag?: string;
        /**
         * 位置，1-主客区/大堂 2-商家入口 3-入口通道 4-独立房间/包间 5-通往洗手间过道 6-洗手间 7-商家外摆区/店外公共区 8-店外墙面(非临街) 9-店外墙面(临街)
         */
        site?: string;
        /**
         * 稳定性，1-固定 2-半固定 3-移动 4-临时
         */
        stability?: string;
        /**
         * 相册
         */
        photo?: Array<string>;
        /**
         * 投放推介
         */
        description?: string;
        /**
         * 设计注意事项
         */
        design_attention?: string;
        /**
         * 施工注意事项
         */
        construction_attention?: string;
        /**
         * 广告位ID
         */
        id: string;
    };
    path?: never;
    query?: never;
    url: '/space/update';
};

export type PostSpaceUpdateResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: string;
    };
};

export type PostSpaceUpdateResponse = PostSpaceUpdateResponses[keyof PostSpaceUpdateResponses];

export type PostSpaceDeleteData = {
    body?: {
        /**
         * 广告位ID
         */
        id: string;
    };
    path?: never;
    query?: never;
    url: '/space/delete';
};

export type PostSpaceDeleteResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: string;
    };
};

export type PostSpaceDeleteResponse = PostSpaceDeleteResponses[keyof PostSpaceDeleteResponses];

export type PostSpaceUpdateStateData = {
    body?: {
        /**
         * 广告位ID
         */
        id: string;
        /**
         * 状态 1-启用 2-禁用
         */
        state: string;
    };
    path?: never;
    query?: never;
    url: '/space/updateState';
};

export type PostSpaceUpdateStateResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: string;
    };
};

export type PostSpaceUpdateStateResponse = PostSpaceUpdateStateResponses[keyof PostSpaceUpdateStateResponses];

export type GetDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/';
};

export type GetDashboardResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            /**
             * 商圈总数
             */
            cbdCount: number;
            /**
             * 物业小区总数
             */
            partCount: number;
            /**
             * 铺位总数
             */
            positionCount: number;
            /**
             * 商家总数
             */
            shopCount: number;
            /**
             * 广告位总数
             */
            spaceCount: number;
            /**
             * 广告活动总数
             */
            campaignCount: number;
        };
    };
};

export type GetDashboardResponse = GetDashboardResponses[keyof GetDashboardResponses];

export type GetDashboardRecentShopsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: string;
    };
    url: '/dashboard/recent-shops';
};

export type GetDashboardRecentShopsResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: Array<{
            id?: string;
            shop_no?: string;
            trademark?: string;
            branch?: string | null;
            type?: string;
            type_tag?: string | null;
            business_type?: string;
            verify_status?: boolean;
            cbd?: {
                id?: string;
                name?: string;
            };
            part?: {
                id?: string;
                name?: string;
            };
            createdAt?: Date;
        }>;
    };
};

export type GetDashboardRecentShopsResponse = GetDashboardRecentShopsResponses[keyof GetDashboardRecentShopsResponses];

export type GetDashboardCbdDistributionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/cbd-distribution';
};

export type GetDashboardCbdDistributionResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: Array<{
            id?: string;
            name?: string;
            district?: string;
            shopCount?: number;
            partCount?: number;
        }>;
    };
};

export type GetDashboardCbdDistributionResponse = GetDashboardCbdDistributionResponses[keyof GetDashboardCbdDistributionResponses];

export type GetDashboardShopTypeDistributionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/shop-type-distribution';
};

export type GetDashboardShopTypeDistributionResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: Array<{
            type?: string;
            count?: number;
        }>;
    };
};

export type GetDashboardShopTypeDistributionResponse = GetDashboardShopTypeDistributionResponses[keyof GetDashboardShopTypeDistributionResponses];

export type GetAuditLogData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        operationType?: string;
        targetType?: string;
        operatorId?: string;
        startDate?: string;
        endDate?: string;
        keyword?: string;
    };
    url: '/auditLog/';
};

export type GetAuditLogResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            items: Array<{
                id: string;
                operationType: string;
                targetType: string;
                targetId: string;
                targetName: string;
                content: string;
                operatorId: string;
                operatorName: string;
                operationTime: string;
                details?: {
                    [key: string]: string;
                };
                ipAddress: string | null;
                userAgent: string | null;
            }>;
            total: number;
            page: number;
            pageSize: number;
            totalPages: number;
        };
    };
};

export type GetAuditLogResponse = GetAuditLogResponses[keyof GetAuditLogResponses];

export type GetAuditLogByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/auditLog/{id}';
};

export type GetAuditLogByIdResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            id: string;
            operationType: string;
            targetType: string;
            targetId: string;
            targetName: string;
            content: string;
            operatorId: string;
            operatorName: string;
            operationTime: string;
            details?: {
                [key: string]: string;
            };
            ipAddress: string | null;
            userAgent: string | null;
        };
    };
};

export type GetAuditLogByIdResponse = GetAuditLogByIdResponses[keyof GetAuditLogByIdResponses];

export type GetAuditLogStatsOperationTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auditLog/stats/operation-types';
};

export type GetAuditLogStatsOperationTypesResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: Array<{
            operationType?: string;
            count?: number;
        }>;
    };
};

export type GetAuditLogStatsOperationTypesResponse = GetAuditLogStatsOperationTypesResponses[keyof GetAuditLogStatsOperationTypesResponses];

export type GetAuditLogStatsRecentActivityData = {
    body?: never;
    path?: never;
    query?: {
        days?: string;
    };
    url: '/auditLog/stats/recent-activity';
};

export type GetAuditLogStatsRecentActivityResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: Array<{
            date?: Date;
            count?: number;
        }>;
    };
};

export type GetAuditLogStatsRecentActivityResponse = GetAuditLogStatsRecentActivityResponses[keyof GetAuditLogStatsRecentActivityResponses];

export type ClientOptions = {
    baseUrl: string;
};
