// This file is auto-generated by @hey-api/openapi-ts

export const AuditLogSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        operationType: {
            type: 'string'
        },
        targetType: {
            type: 'string'
        },
        targetId: {
            type: 'string'
        },
        targetName: {
            type: 'string'
        },
        content: {
            type: 'string'
        },
        operatorId: {
            type: 'string'
        },
        operatorName: {
            type: 'string'
        },
        operationTime: {
            type: 'string'
        },
        details: {
            type: 'object',
            additionalProperties: {
                type: 'string'
            },
            properties: {}
        },
        ipAddress: {
            type: 'string',
            nullable: true
        },
        userAgent: {
            type: 'string',
            nullable: true
        }
    },
    required: ['id', 'operationType', 'targetType', 'targetId', 'targetName', 'content', 'operatorId', 'operatorName', 'operationTime', 'ipAddress', 'userAgent'],
    additionalProperties: false,
    title: 'AuditLog'
} as const;

export const PositionSchema = {
    type: 'object',
    properties: {
        positionId: {
            type: 'string'
        },
        position_no: {
            type: 'string'
        },
        shopId: {
            type: 'string',
            nullable: true
        },
        shop_no: {
            type: 'string',
            nullable: true
        },
        total_space: {
            type: 'number'
        },
        put_space: {
            type: 'number'
        },
        price_base: {
            type: 'number'
        },
        verified: {
            type: 'boolean'
        },
        displayed: {
            type: 'boolean'
        },
        type: {
            type: 'string',
            nullable: true
        },
        type_tag: {
            type: 'string',
            nullable: true
        },
        photo: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        remark: {
            type: 'string',
            nullable: true
        },
        business_hours: {
            type: 'array',
            items: {
                type: 'number'
            }
        }
    },
    required: ['positionId', 'position_no', 'shopId', 'shop_no', 'total_space', 'put_space', 'price_base', 'verified', 'displayed', 'type', 'type_tag', 'photo', 'remark', 'business_hours'],
    additionalProperties: false,
    title: 'Position'
} as const;

export const spaceResponseSchemaSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        type: {
            type: 'string'
        },
        setting: {
            type: 'object',
            additionalProperties: {
                type: 'string'
            },
            properties: {}
        },
        count: {
            type: 'number'
        },
        state: {
            type: 'string'
        },
        price_factor: {
            type: 'number',
            exclusiveMinimum: true,
            default: 1,
            description: '价格因子',
            minimum: 0
        },
        updatedAt: {
            type: 'string'
        },
        shopId: {
            type: 'string'
        },
        shop: {
            type: 'object',
            properties: {
                trademark: {
                    type: 'string',
                    description: '商标'
                },
                shop_no: {
                    type: 'string',
                    description: '门店号'
                },
                branch: {
                    type: 'string',
                    description: '分店名称'
                }
            },
            additionalProperties: false
        },
        tag: {
            type: 'string',
            description: '分类标签'
        },
        site: {
            type: 'string',
            description: '位置，1-主客区/大堂 2-商家入口 3-入口通道 4-独立房间/包间 5-通往洗手间过道 6-洗手间 7-商家外摆区/店外公共区 8-店外墙面(非临街) 9-店外墙面(临街)'
        },
        stability: {
            type: 'string',
            description: '稳定性，1-固定 2-半固定 3-移动 4-临时'
        },
        photo: {
            type: 'array',
            items: {
                type: 'string'
            },
            description: '相册'
        },
        description: {
            type: 'string',
            description: '投放推介'
        },
        design_attention: {
            type: 'string',
            description: '设计注意事项'
        },
        construction_attention: {
            type: 'string',
            description: '施工注意事项'
        }
    },
    required: ['id', 'type', 'setting', 'count', 'state', 'updatedAt', 'shopId'],
    additionalProperties: false,
    title: 'spaceResponseSchema'
} as const;

export const shopResponseSchemaSchema = {
    type: 'object',
    properties: {
        shopId: {
            type: 'string'
        },
        shop_no: {
            type: 'string'
        },
        trademark: {
            type: 'string'
        },
        branch: {
            type: 'string',
            nullable: true
        },
        total_space: {
            type: 'number'
        },
        put_space: {
            type: 'number'
        },
        price_base: {
            type: 'number'
        },
        verified: {
            type: 'boolean'
        },
        displayed: {
            type: 'boolean'
        },
        type: {
            type: 'string'
        },
        type_tag: {
            type: 'string',
            nullable: true
        },
        photo: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        remark: {
            type: 'string',
            nullable: true
        },
        business_hours: {
            type: 'array',
            items: {
                type: 'number'
            }
        },
        total_area: {
            type: 'number',
            nullable: true
        },
        customer_area: {
            type: 'number',
            nullable: true
        },
        clerk_count: {
            type: 'number',
            nullable: true
        },
        business_type: {
            type: 'string'
        },
        duration: {
            type: 'string'
        },
        sex: {
            type: 'string'
        },
        age: {
            type: 'array',
            items: {
                type: 'number'
            }
        },
        id_tag: {
            type: 'string',
            nullable: true
        },
        sign_photo: {
            type: 'string',
            nullable: true
        },
        contact_type: {
            type: 'string'
        },
        shop_description: {
            type: 'string',
            description: '商家简介'
        },
        put_description: {
            type: 'string',
            description: '投放简介'
        },
        classify_tag: {
            type: 'string',
            description: '分类标签'
        }
    },
    required: ['shopId', 'trademark', 'branch', 'total_space', 'put_space', 'price_base', 'verified', 'displayed', 'type', 'type_tag', 'photo', 'remark', 'business_hours', 'total_area', 'customer_area', 'clerk_count', 'business_type', 'duration', 'sex', 'age', 'id_tag', 'sign_photo', 'contact_type'],
    additionalProperties: false,
    title: 'shopResponseSchema'
} as const;

export const partResponseSchemaSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        sequence: {
            type: 'number'
        },
        total_space: {
            type: 'number'
        }
    },
    required: ['id', 'name', 'sequence', 'total_space'],
    additionalProperties: false,
    title: 'partResponseSchema'
} as const;

export const districtResponseSchemaSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        }
    },
    required: ['id', 'name'],
    additionalProperties: false,
    title: 'districtResponseSchema'
} as const;

export const cityResponseSchemaSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        }
    },
    required: ['id', 'name'],
    additionalProperties: false,
    title: 'cityResponseSchema'
} as const;

export const cbdResponseSchemaSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        addr: {
            type: 'string',
            nullable: true
        }
    },
    required: ['id', 'name', 'addr'],
    additionalProperties: false,
    title: 'cbdResponseSchema'
} as const;

export const PaymentMethodSchema = {
    type: 'object',
    properties: {
        id: {
            description: '自动增长的主键',
            default: 0,
            type: 'number'
        },
        productId: {
            description: '产品ID',
            minimum: 1,
            type: 'number'
        },
        platformId: {
            description: '平台ID',
            minimum: 1,
            type: 'number'
        },
        type: {
            description: '支付方式类型',
            minLength: 1,
            type: 'string'
        },
        transactionType: {
            description: '交易类型，例如 wallet、card、bankTransfer 等',
            minLength: 1,
            type: 'string'
        },
        imageLink: {
            description: '图片链接或资源路径',
            minLength: 1,
            type: 'string'
        },
        acquiringMode: {
            description: '收单模式，如 direct、link、checkout 等',
            minLength: 1,
            type: 'string'
        },
        processingCurrencies: {
            description: '处理币种，多个币种以逗号分隔',
            minLength: 1,
            type: 'string'
        },
        productChannelId: {
            description: '产品渠道ID',
            minimum: 1,
            type: 'number'
        },
        merchantId: {
            description: '商户ID',
            minimum: 1,
            type: 'number'
        },
        providerId: {
            description: '服务提供商ID',
            minimum: 1,
            type: 'number'
        },
        platformName: {
            description: '平台名称',
            minLength: 1,
            type: 'string'
        },
        channelId: {
            description: '渠道ID',
            minimum: 1,
            type: 'number'
        },
        markup: {
            description: '加价比例（浮点数）',
            minimum: 0,
            type: 'number'
        },
        needField: {
            description: '保存必要字段的 JSON 字符串',
            default: '{}',
            type: 'string'
        },
        regular: {
            description: '保存常规字段的 JSON 字符串',
            default: '{}',
            type: 'string'
        },
        supportedConsumer: {
            description: '支持的消费者国家代码，多个以逗号分隔',
            default: '',
            type: 'string'
        },
        currencyInfo: {
            description: '关联的币种信息数组',
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    id: {
                        description: '自动增长的主键',
                        default: 0,
                        type: 'number'
                    },
                    currencyNameEn: {
                        description: '货币的英文名称',
                        minLength: 1,
                        default: '',
                        type: 'string'
                    },
                    currencyName: {
                        description: '货币的本地名称',
                        minLength: 1,
                        default: '',
                        type: 'string'
                    },
                    currencyCode: {
                        description: 'ISO 货币代码，例如 USD',
                        minLength: 1,
                        default: '',
                        type: 'string'
                    },
                    paymentMethodId: {
                        description: '关联 PaymentMethod 的主键',
                        minimum: 1,
                        type: 'number'
                    }
                },
                required: ['id', 'currencyNameEn', 'currencyName', 'currencyCode', 'paymentMethodId']
            }
        }
    },
    required: ['id', 'productId', 'platformId', 'type', 'transactionType', 'imageLink', 'acquiringMode', 'processingCurrencies', 'productChannelId', 'merchantId', 'providerId', 'platformName', 'channelId', 'markup', 'needField', 'regular', 'supportedConsumer', 'currencyInfo'],
    title: 'PaymentMethod'
} as const;

export const PaymentMethodListSchemaSchema = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    id: {
                        description: '自动增长的主键',
                        default: 0,
                        type: 'number'
                    },
                    productId: {
                        description: '产品ID',
                        minimum: 1,
                        type: 'number'
                    },
                    platformId: {
                        description: '平台ID',
                        minimum: 1,
                        type: 'number'
                    },
                    type: {
                        description: '支付方式类型',
                        minLength: 1,
                        type: 'string'
                    },
                    transactionType: {
                        description: '交易类型，例如 wallet、card、bankTransfer 等',
                        minLength: 1,
                        type: 'string'
                    },
                    imageLink: {
                        description: '图片链接或资源路径',
                        minLength: 1,
                        type: 'string'
                    },
                    acquiringMode: {
                        description: '收单模式，如 direct、link、checkout 等',
                        minLength: 1,
                        type: 'string'
                    },
                    processingCurrencies: {
                        description: '处理币种，多个币种以逗号分隔',
                        minLength: 1,
                        type: 'string'
                    },
                    productChannelId: {
                        description: '产品渠道ID',
                        minimum: 1,
                        type: 'number'
                    },
                    merchantId: {
                        description: '商户ID',
                        minimum: 1,
                        type: 'number'
                    },
                    providerId: {
                        description: '服务提供商ID',
                        minimum: 1,
                        type: 'number'
                    },
                    platformName: {
                        description: '平台名称',
                        minLength: 1,
                        type: 'string'
                    },
                    channelId: {
                        description: '渠道ID',
                        minimum: 1,
                        type: 'number'
                    },
                    markup: {
                        description: '加价比例（浮点数）',
                        minimum: 0,
                        type: 'number'
                    },
                    needField: {
                        description: '保存必要字段的 JSON 字符串',
                        default: '{}',
                        type: 'string'
                    },
                    regular: {
                        description: '保存常规字段的 JSON 字符串',
                        default: '{}',
                        type: 'string'
                    },
                    supportedConsumer: {
                        description: '支持的消费者国家代码，多个以逗号分隔',
                        default: '',
                        type: 'string'
                    },
                    currencyInfo: {
                        description: '关联的币种信息数组',
                        type: 'array',
                        items: {
                            type: 'object',
                            properties: {
                                id: {
                                    description: '自动增长的主键',
                                    default: 0,
                                    type: 'number'
                                },
                                currencyNameEn: {
                                    description: '货币的英文名称',
                                    minLength: 1,
                                    default: '',
                                    type: 'string'
                                },
                                currencyName: {
                                    description: '货币的本地名称',
                                    minLength: 1,
                                    default: '',
                                    type: 'string'
                                },
                                currencyCode: {
                                    description: 'ISO 货币代码，例如 USD',
                                    minLength: 1,
                                    default: '',
                                    type: 'string'
                                },
                                paymentMethodId: {
                                    description: '关联 PaymentMethod 的主键',
                                    minimum: 1,
                                    type: 'number'
                                }
                            },
                            required: ['id', 'currencyNameEn', 'currencyName', 'currencyCode', 'paymentMethodId']
                        }
                    }
                },
                required: ['id', 'productId', 'platformId', 'type', 'transactionType', 'imageLink', 'acquiringMode', 'processingCurrencies', 'productChannelId', 'merchantId', 'providerId', 'platformName', 'channelId', 'markup', 'needField', 'regular', 'supportedConsumer', 'currencyInfo'],
                title: 'PaymentMethod'
            }
        },
        code: {
            default: '0',
            pattern: '^[0-9]+$',
            type: 'string'
        },
        msg: {
            default: 'Success',
            type: 'string'
        },
        serverTime: {
            default: 1741250430788,
            type: 'number'
        },
        success: {
            default: true,
            type: 'boolean'
        }
    },
    required: ['data', 'code', 'msg', 'serverTime', 'success'],
    title: 'PaymentMethodListSchema'
} as const;

export const OrderStatusSchemaSchema = {
    type: 'object',
    properties: {
        data: {
            description: '订单状态对象，包含详细的支付信息、订单信息和交易信息',
            type: 'object',
            properties: {
                acquiringMode: {
                    description: '收单模式',
                    type: 'string'
                },
                buyerId: {
                    description: '买家 ID',
                    type: 'string'
                },
                channelId: {
                    description: '渠道 ID',
                    type: 'number'
                },
                channelRatesId: {
                    description: '渠道费率 ID',
                    type: 'number'
                },
                channelRequestTime: {
                    description: '渠道请求时间 (Unix 时间戳)',
                    type: 'number'
                },
                country: {
                    minLength: 2,
                    maxLength: 3,
                    description: '国家代码 (ISO 3166-1 Alpha-2/Alpha-3)',
                    type: 'string'
                },
                currency: {
                    minLength: 3,
                    maxLength: 3,
                    description: '货币代码 (ISO 4217)',
                    type: 'string'
                },
                downstreamEstimatedAmount: {
                    minimum: 0,
                    description: '预估下游金额',
                    type: 'number'
                },
                downstreamEstimatedFee: {
                    minimum: 0,
                    description: '预估下游费用',
                    type: 'number'
                },
                downstreamFee: {
                    description: '下游费用详情',
                    type: 'string'
                },
                downstreamFeeC: {
                    description: '下游费用 C 版本',
                    type: 'string'
                },
                downstreamFixedFee: {
                    description: '下游固定费用',
                    type: 'string'
                },
                downstreamGatewayFee: {
                    description: '下游网关费用',
                    type: 'string'
                },
                downstreamOrderNo: {
                    description: '下游订单号',
                    type: 'string'
                },
                downstreamOrderNoOrigin: {
                    description: '原始下游订单号',
                    type: 'string'
                },
                downstreamRedirectUrl: {
                    format: 'uri',
                    description: '下游跳转 URL',
                    type: 'string'
                },
                downstreamTxRate: {
                    description: '下游交易汇率',
                    type: 'string'
                },
                errorMsg: {
                    description: '错误信息',
                    type: 'string'
                },
                estimatedAmount: {
                    minimum: 0,
                    description: '预估金额',
                    type: 'number'
                },
                estimatedExchangeRate: {
                    description: '预估汇率',
                    type: 'string'
                },
                failReason: {
                    description: '失败原因',
                    type: 'string'
                },
                freezeType: {
                    description: '冻结类型',
                    type: 'number'
                },
                id: {
                    description: '订单 ID',
                    type: 'number'
                },
                merchantCurrency: {
                    minLength: 3,
                    maxLength: 3,
                    description: '商户货币代码',
                    type: 'string'
                },
                merchantId: {
                    description: '商户 ID',
                    type: 'number'
                },
                merchantName: {
                    description: '商户名称',
                    type: 'string'
                },
                merchantOrderAmount: {
                    minimum: 0,
                    description: '商户订单金额',
                    type: 'number'
                },
                merchantRequestTime: {
                    description: '商户请求时间 (Unix 时间戳)',
                    type: 'number'
                },
                orderAmount: {
                    minimum: 0,
                    description: '订单金额',
                    type: 'number'
                },
                orderCreateTime: {
                    description: '订单创建时间 (Unix 时间戳)',
                    type: 'number'
                },
                orderStatus: {
                    description: '订单状态，例如 PENDING, SUCCESS, FAILED',
                    type: 'string'
                },
                orderType: {
                    description: '订单类型',
                    type: 'string'
                },
                origin: {
                    description: '订单来源',
                    type: 'string'
                },
                paymentExchange: {
                    description: '支付兑换金额',
                    type: 'number'
                },
                paymentExchangeRate: {
                    description: '支付兑换汇率',
                    type: 'number'
                },
                paymentMethod: {
                    description: '支付方式',
                    type: 'string'
                },
                paymentTxMarkup: {
                    description: '支付交易加成',
                    type: 'number'
                },
                paymentTxMarkupUsd: {
                    description: '美元支付交易加成',
                    type: 'number'
                },
                platformId: {
                    description: '平台 ID',
                    type: 'number'
                },
                platformOrderNo: {
                    description: '平台订单号',
                    type: 'string'
                },
                productChannelId: {
                    description: '产品渠道 ID',
                    type: 'number'
                },
                productId: {
                    description: '产品 ID',
                    type: 'number'
                },
                profit: {
                    description: '利润',
                    type: 'number'
                },
                providerId: {
                    description: '供应商 ID',
                    type: 'number'
                },
                requestStatus: {
                    description: '请求状态',
                    type: 'number'
                },
                reviewStatus: {
                    description: '审核状态',
                    type: 'string'
                },
                riskType: {
                    description: '风险类型',
                    type: 'number'
                },
                sessionId: {
                    description: '会话 ID',
                    type: 'string'
                },
                settlementCurrency: {
                    minLength: 3,
                    maxLength: 3,
                    description: '结算货币代码',
                    type: 'string'
                },
                settlementCycle: {
                    description: '结算周期',
                    type: 'string'
                },
                transactionType: {
                    description: '交易类型',
                    type: 'string'
                },
                upstreamEstimatedAmount: {
                    minimum: 0,
                    description: '上游预估金额',
                    type: 'number'
                },
                upstreamEstimatedFee: {
                    minimum: 0,
                    description: '上游预估费用',
                    type: 'number'
                },
                upstreamFee: {
                    description: '上游费用',
                    type: 'string'
                },
                upstreamFixedFee: {
                    description: '上游固定费用',
                    type: 'string'
                },
                upstreamGatewayFee: {
                    description: '上游网关费用',
                    type: 'string'
                },
                upstreamOrderNo: {
                    description: '上游订单号',
                    type: 'string'
                },
                upstreamStatus: {
                    description: '上游状态',
                    type: 'string'
                },
                upstreamTxRate: {
                    description: '上游交易汇率',
                    type: 'string'
                }
            },
            required: ['acquiringMode', 'buyerId', 'channelId', 'channelRatesId', 'channelRequestTime', 'country', 'currency', 'downstreamEstimatedAmount', 'downstreamEstimatedFee', 'downstreamFee', 'downstreamFeeC', 'downstreamFixedFee', 'downstreamGatewayFee', 'downstreamOrderNo', 'downstreamOrderNoOrigin', 'downstreamRedirectUrl', 'downstreamTxRate', 'errorMsg', 'estimatedAmount', 'estimatedExchangeRate', 'failReason', 'freezeType', 'id', 'merchantCurrency', 'merchantId', 'merchantName', 'merchantOrderAmount', 'merchantRequestTime', 'orderAmount', 'orderCreateTime', 'orderStatus', 'orderType', 'origin', 'paymentExchange', 'paymentExchangeRate', 'paymentMethod', 'platformId', 'platformOrderNo', 'productChannelId', 'productId', 'profit', 'providerId', 'requestStatus', 'reviewStatus', 'riskType', 'sessionId', 'settlementCurrency', 'settlementCycle', 'transactionType', 'upstreamEstimatedAmount', 'upstreamEstimatedFee', 'upstreamFee', 'upstreamFixedFee', 'upstreamGatewayFee', 'upstreamOrderNo', 'upstreamStatus', 'upstreamTxRate']
        },
        code: {
            default: '0',
            pattern: '^[0-9]+$',
            type: 'string'
        },
        msg: {
            default: 'Success',
            type: 'string'
        },
        serverTime: {
            default: 1741250430788,
            type: 'number'
        },
        success: {
            default: true,
            type: 'boolean'
        }
    },
    required: ['data', 'code', 'msg', 'serverTime', 'success'],
    title: 'OrderStatusSchema'
} as const;

export const AllInOneOutputSchemaSchema = {
    type: 'object',
    properties: {
        data: {
            description: '完整的 API 响应数据，包含支付操作、订单信息、客户信息等',
            type: 'object',
            properties: {
                action: {
                    description: '支付操作相关信息',
                    type: 'object',
                    properties: {
                        paymentMethodType: {
                            anyOf: [
                                {
                                    type: 'string',
                                    enum: ['alipay']
                                },
                                {
                                    type: 'string',
                                    enum: ['americanexpress']
                                },
                                {
                                    type: 'string',
                                    enum: ['applepay']
                                },
                                {
                                    type: 'string',
                                    enum: ['applepayus']
                                },
                                {
                                    type: 'string',
                                    enum: ['bancomatpay']
                                },
                                {
                                    type: 'string',
                                    enum: ['blikoneclick']
                                },
                                {
                                    type: 'string',
                                    enum: ['blik']
                                },
                                {
                                    type: 'string',
                                    enum: ['bitpay']
                                },
                                {
                                    type: 'string',
                                    enum: ['cashapppay']
                                },
                                {
                                    type: 'string',
                                    enum: ['duitnow']
                                },
                                {
                                    type: 'string',
                                    enum: ['eps']
                                },
                                {
                                    type: 'string',
                                    enum: ['fpxonlinebanking']
                                },
                                {
                                    type: 'string',
                                    enum: ['fpx']
                                },
                                {
                                    type: 'string',
                                    enum: ['finlandbanks']
                                },
                                {
                                    type: 'string',
                                    enum: ['giropay']
                                },
                                {
                                    type: 'string',
                                    enum: ['gopay']
                                },
                                {
                                    type: 'string',
                                    enum: ['googlepay']
                                },
                                {
                                    type: 'string',
                                    enum: ['googlepayus']
                                },
                                {
                                    type: 'string',
                                    enum: ['indonesiabanks']
                                },
                                {
                                    type: 'string',
                                    enum: ['jcb']
                                },
                                {
                                    type: 'string',
                                    enum: ['konbini']
                                },
                                {
                                    type: 'string',
                                    enum: ['koreandomesticcards']
                                },
                                {
                                    type: 'string',
                                    enum: ['mbbank']
                                },
                                {
                                    type: 'string',
                                    enum: ['mastercard']
                                },
                                {
                                    type: 'string',
                                    enum: ['mybank']
                                },
                                {
                                    type: 'string',
                                    enum: ['oxxo']
                                },
                                {
                                    type: 'string',
                                    enum: ['pix']
                                },
                                {
                                    type: 'string',
                                    enum: ['payeasy']
                                },
                                {
                                    type: 'string',
                                    enum: ['paypal']
                                },
                                {
                                    type: 'string',
                                    enum: ['payconiq']
                                },
                                {
                                    type: 'string',
                                    enum: ['paysafecard']
                                },
                                {
                                    type: 'string',
                                    enum: ['p24']
                                },
                                {
                                    type: 'string',
                                    enum: ['przelewy24']
                                },
                                {
                                    type: 'string',
                                    enum: ['przelewy24p24']
                                },
                                {
                                    type: 'string',
                                    enum: ['satispay']
                                },
                                {
                                    type: 'string',
                                    enum: ['sepadebit']
                                },
                                {
                                    type: 'string',
                                    enum: ['sepaddmodelc']
                                },
                                {
                                    type: 'string',
                                    enum: ['sepaddmodela']
                                },
                                {
                                    type: 'string',
                                    enum: ['skrill']
                                },
                                {
                                    type: 'string',
                                    enum: ['todito']
                                },
                                {
                                    type: 'string',
                                    enum: ['tosspay']
                                },
                                {
                                    type: 'string',
                                    enum: ['touchngo']
                                },
                                {
                                    type: 'string',
                                    enum: ['trustly']
                                },
                                {
                                    type: 'string',
                                    enum: ['upi']
                                },
                                {
                                    type: 'string',
                                    enum: ['unionpay']
                                },
                                {
                                    type: 'string',
                                    enum: ['visa']
                                },
                                {
                                    type: 'string',
                                    enum: ['wechatpay']
                                },
                                {
                                    type: 'string',
                                    enum: ['zip']
                                },
                                {
                                    type: 'string',
                                    enum: ['zipus']
                                },
                                {
                                    type: 'string',
                                    enum: ['pbba']
                                },
                                {
                                    type: 'string',
                                    enum: ['paybybankapp']
                                },
                                {
                                    type: 'string',
                                    enum: ['paybybankapppbba']
                                },
                                {
                                    type: 'string',
                                    enum: ['payu']
                                },
                                {
                                    type: 'string',
                                    enum: ['klasha']
                                },
                                {
                                    type: 'string',
                                    enum: ['card']
                                },
                                {
                                    type: 'string',
                                    enum: ['banktransaction']
                                },
                                {
                                    type: 'string',
                                    enum: ['mobilemoney']
                                },
                                {
                                    type: 'string',
                                    enum: ['mpesa']
                                },
                                {
                                    type: 'string',
                                    enum: ['wemabank']
                                },
                                {
                                    type: 'string',
                                    enum: ['cardafrica']
                                },
                                {
                                    type: 'string',
                                    enum: ['afterpay']
                                },
                                {
                                    type: 'string',
                                    enum: ['klarna']
                                },
                                {
                                    type: 'string',
                                    enum: ['payovertimeklarna']
                                },
                                {
                                    type: 'string',
                                    enum: ['paylaterklarna']
                                },
                                {
                                    type: 'string',
                                    enum: ['paynowklarna']
                                },
                                {
                                    type: 'string',
                                    enum: ['banktransferklarna']
                                },
                                {
                                    type: 'string',
                                    enum: ['directdebitklarna']
                                },
                                {
                                    type: 'string',
                                    enum: ['upiinstore']
                                },
                                {
                                    type: 'string',
                                    enum: ['mbway']
                                },
                                {
                                    type: 'string',
                                    enum: ['thaibanks']
                                },
                                {
                                    type: 'string',
                                    enum: ['thaibanksapp']
                                },
                                {
                                    type: 'string',
                                    enum: ['skrilltap']
                                },
                                {
                                    type: 'string',
                                    enum: ['clearpay']
                                },
                                {
                                    type: 'string',
                                    enum: ['onlinebanking']
                                },
                                {
                                    type: 'string',
                                    enum: ['doku']
                                },
                                {
                                    type: 'string',
                                    enum: ['shoppepay']
                                },
                                {
                                    type: 'string',
                                    enum: ['shopeepay']
                                },
                                {
                                    type: 'string',
                                    enum: ['truemoney']
                                },
                                {
                                    type: 'string',
                                    enum: ['kbank']
                                },
                                {
                                    type: 'string',
                                    enum: ['kodd']
                                },
                                {
                                    type: 'string',
                                    enum: ['thaiqr']
                                },
                                {
                                    type: 'string',
                                    enum: ['cardus']
                                },
                                {
                                    type: 'string',
                                    enum: ['cardsus']
                                },
                                {
                                    type: 'string',
                                    enum: ['kakaopay']
                                },
                                {
                                    type: 'string',
                                    enum: ['tmn']
                                },
                                {
                                    type: 'string',
                                    enum: ['mpay']
                                },
                                {
                                    type: 'string',
                                    enum: ['rabbitlinepay']
                                },
                                {
                                    type: 'string',
                                    enum: ['boost']
                                },
                                {
                                    type: 'string',
                                    enum: ['bpi']
                                },
                                {
                                    type: 'string',
                                    enum: ['tng']
                                },
                                {
                                    type: 'string',
                                    enum: ['dana']
                                },
                                {
                                    type: 'string',
                                    enum: ['alipayhk']
                                },
                                {
                                    type: 'string',
                                    enum: ['gcash']
                                },
                                {
                                    type: 'string',
                                    enum: ['tsp']
                                },
                                {
                                    type: 'string',
                                    enum: ['tinaba']
                                },
                                {
                                    type: 'string',
                                    enum: ['kredivo']
                                },
                                {
                                    type: 'string',
                                    enum: ['naverpay']
                                },
                                {
                                    type: 'string',
                                    enum: ['kplus']
                                },
                                {
                                    type: 'string',
                                    enum: ['billease']
                                },
                                {
                                    type: 'string',
                                    enum: ['alipaycn']
                                },
                                {
                                    type: 'string',
                                    enum: ['creditcardupop']
                                },
                                {
                                    type: 'string',
                                    enum: ['alipayup']
                                },
                                {
                                    type: 'string',
                                    enum: ['upop']
                                },
                                {
                                    type: 'string',
                                    enum: ['wechatpayup']
                                },
                                {
                                    type: 'string',
                                    enum: ['qp']
                                },
                                {
                                    type: 'string',
                                    enum: ['creditcardvm']
                                }
                            ]
                        },
                        url: {
                            format: 'uri',
                            description: '支付页面 URL',
                            type: 'string'
                        },
                        applinkUrl: {
                            format: 'uri',
                            description: '应用程序跳转链接',
                            type: 'string'
                        },
                        schemeUrl: {
                            format: 'uri',
                            description: 'Scheme URL',
                            type: 'string'
                        },
                        payUrl: {
                            format: 'uri',
                            description: '支付 URL',
                            type: 'string'
                        },
                        method: {
                            description: 'HTTP 方法，例如 GET, POST',
                            type: 'string'
                        },
                        type: {
                            description: '支付操作类型，可选值：redirect、pin、avs、sms、qrcode',
                            anyOf: [
                                {
                                    type: 'string',
                                    enum: ['redirect']
                                },
                                {
                                    type: 'string',
                                    enum: ['pin']
                                },
                                {
                                    type: 'string',
                                    enum: ['avs']
                                },
                                {
                                    type: 'string',
                                    enum: ['sms']
                                },
                                {
                                    type: 'string',
                                    enum: ['qrcode']
                                }
                            ]
                        },
                        qrCode: {
                            description: '支付二维码内容',
                            type: 'string'
                        },
                        message: {
                            description: '支付提示信息',
                            type: 'string'
                        },
                        fields: {
                            description: '需要填写的支付字段列表',
                            type: 'array',
                            items: {
                                type: 'string'
                            }
                        }
                    },
                    required: ['paymentMethodType', 'url', 'method', 'type', 'qrCode']
                },
                amount: {
                    description: '订单金额信息',
                    type: 'object',
                    properties: {
                        currency: {
                            minLength: 3,
                            maxLength: 3,
                            default: 'USD',
                            description: '货币类型，ISO 4217 三位字母代码',
                            type: 'string'
                        },
                        value: {
                            minimum: 0,
                            description: '金额的最小单位值，例如分、厘',
                            type: 'number'
                        }
                    },
                    required: ['currency', 'value']
                },
                order: {
                    description: '订单信息',
                    type: 'object',
                    properties: {
                        account: {
                            description: '付款账户唯一标识',
                            type: 'string'
                        },
                        amount: {
                            description: '订单金额信息',
                            type: 'object',
                            properties: {
                                currency: {
                                    minLength: 3,
                                    maxLength: 3,
                                    default: 'USD',
                                    description: '货币类型，ISO 4217 三位字母代码',
                                    type: 'string'
                                },
                                value: {
                                    minimum: 0,
                                    description: '金额的最小单位值，例如分、厘',
                                    type: 'number'
                                }
                            },
                            required: ['currency', 'value']
                        },
                        accountName: {
                            description: '账户持有人姓名',
                            type: 'string'
                        },
                        bank: {
                            description: '银行名称',
                            type: 'string'
                        },
                        expiresAt: {
                            format: 'date-time',
                            description: '订单过期时间（ISO 8601 格式）',
                            type: 'string'
                        },
                        note: {
                            description: '订单备注信息',
                            type: 'string'
                        }
                    },
                    required: ['account', 'amount', 'accountName', 'bank', 'expiresAt', 'note']
                },
                customer: {
                    description: '客户信息',
                    type: 'object',
                    properties: {
                        id: {
                            description: '客户唯一 ID',
                            type: 'string'
                        },
                        phone: {
                            pattern: '^\\+?[1-9]\\d{1,14}$',
                            description: '客户电话号码，符合 E.164 格式',
                            type: 'string'
                        },
                        name: {
                            minLength: 1,
                            description: '客户姓名',
                            type: 'string'
                        },
                        email: {
                            format: 'email',
                            description: '客户电子邮件地址',
                            type: 'string'
                        },
                        createdAt: {
                            format: 'date-time',
                            description: '客户创建时间（ISO 8601 格式）',
                            type: 'string'
                        }
                    },
                    required: ['id', 'phone', 'name', 'email', 'createdAt']
                },
                refusalReason: {
                    description: '拒绝原因或错误信息，若交易失败则提供详细信息',
                    type: 'string'
                },
                pspReference: {
                    description: '支付服务提供商的唯一交易参考号',
                    type: 'string'
                },
                reference: {
                    description: '商户的订单参考号',
                    type: 'string'
                },
                resultCode: {
                    default: 'SUCCESS',
                    description: '交易结果代码，例如 SUCCESS, FAILED, PENDING',
                    type: 'string'
                }
            },
            required: ['refusalReason', 'pspReference', 'resultCode']
        },
        code: {
            default: '0',
            pattern: '^[0-9]+$',
            type: 'string'
        },
        msg: {
            default: 'Success',
            type: 'string'
        },
        serverTime: {
            default: 1741250430788,
            type: 'number'
        },
        success: {
            default: true,
            type: 'boolean'
        }
    },
    required: ['data', 'code', 'msg', 'serverTime', 'success'],
    title: 'AllInOneOutputSchema'
} as const;

export const ReferenceInputSchemaSchema = {
    type: 'object',
    properties: {
        reference: {
            minLength: 10,
            maxLength: 64,
            description: '订单号',
            type: 'string'
        }
    },
    required: ['reference'],
    title: 'ReferenceInputSchema'
} as const;

export const TokenInputSchemaSchema = {
    type: 'object',
    properties: {
        token: {
            format: 'uuid',
            type: 'string'
        }
    },
    required: ['token'],
    title: 'TokenInputSchema'
} as const;

export const AmountSchemaSchema = {
    description: '订单金额信息',
    type: 'object',
    properties: {
        currency: {
            minLength: 3,
            maxLength: 3,
            default: 'USD',
            description: '货币类型，ISO 4217 三位字母代码',
            type: 'string'
        },
        value: {
            minimum: 0,
            description: '订单金额，单位为最小货币单位，例如分、厘',
            type: 'number'
        }
    },
    required: ['currency', 'value'],
    title: 'AmountSchema'
} as const;

export const PaymentHeaderSchemaSchema = {
    type: 'object',
    properties: {
        providerId: {
            description: '支付渠道 ID',
            type: 'string'
        },
        merchantId: {
            description: '商户 ID',
            type: 'string'
        },
        appId: {
            description: '应用 ID',
            type: 'string'
        }
    },
    required: ['providerId', 'merchantId', 'appId'],
    title: 'PaymentHeaderSchema'
} as const;

export const PaymentInputSchemaSchema = {
    description: '支付请求数据结构',
    type: 'object',
    properties: {
        amount: {
            description: '订单金额信息',
            type: 'object',
            properties: {
                currency: {
                    minLength: 3,
                    maxLength: 3,
                    default: 'USD',
                    description: '货币类型，ISO 4217 三位字母代码',
                    type: 'string'
                },
                value: {
                    minimum: 0,
                    description: '订单金额，单位为最小货币单位，例如分、厘',
                    type: 'number'
                }
            },
            required: ['currency', 'value']
        },
        countryCode: {
            minLength: 2,
            maxLength: 2,
            default: 'CN',
            description: '国家代码，符合 ISO 3166-1 Alpha-2 标准',
            type: 'string'
        },
        isExchange: {
            default: false,
            description: '是否进行汇率转换',
            type: 'boolean'
        },
        merchantAccount: {
            description: '商户账户名称',
            type: 'string'
        },
        merchantId: {
            description: '商户 ID',
            type: 'string'
        },
        origin: {
            description: '请求来源，例如 xyz.com',
            type: 'string'
        },
        paymentMethod: {
            type: 'object',
            properties: {
                type: {
                    anyOf: [
                        {
                            type: 'string',
                            enum: ['alipay']
                        },
                        {
                            type: 'string',
                            enum: ['americanexpress']
                        },
                        {
                            type: 'string',
                            enum: ['applepay']
                        },
                        {
                            type: 'string',
                            enum: ['applepayus']
                        },
                        {
                            type: 'string',
                            enum: ['bancomatpay']
                        },
                        {
                            type: 'string',
                            enum: ['blikoneclick']
                        },
                        {
                            type: 'string',
                            enum: ['blik']
                        },
                        {
                            type: 'string',
                            enum: ['bitpay']
                        },
                        {
                            type: 'string',
                            enum: ['cashapppay']
                        },
                        {
                            type: 'string',
                            enum: ['duitnow']
                        },
                        {
                            type: 'string',
                            enum: ['eps']
                        },
                        {
                            type: 'string',
                            enum: ['fpxonlinebanking']
                        },
                        {
                            type: 'string',
                            enum: ['fpx']
                        },
                        {
                            type: 'string',
                            enum: ['finlandbanks']
                        },
                        {
                            type: 'string',
                            enum: ['giropay']
                        },
                        {
                            type: 'string',
                            enum: ['gopay']
                        },
                        {
                            type: 'string',
                            enum: ['googlepay']
                        },
                        {
                            type: 'string',
                            enum: ['googlepayus']
                        },
                        {
                            type: 'string',
                            enum: ['indonesiabanks']
                        },
                        {
                            type: 'string',
                            enum: ['jcb']
                        },
                        {
                            type: 'string',
                            enum: ['konbini']
                        },
                        {
                            type: 'string',
                            enum: ['koreandomesticcards']
                        },
                        {
                            type: 'string',
                            enum: ['mbbank']
                        },
                        {
                            type: 'string',
                            enum: ['mastercard']
                        },
                        {
                            type: 'string',
                            enum: ['mybank']
                        },
                        {
                            type: 'string',
                            enum: ['oxxo']
                        },
                        {
                            type: 'string',
                            enum: ['pix']
                        },
                        {
                            type: 'string',
                            enum: ['payeasy']
                        },
                        {
                            type: 'string',
                            enum: ['paypal']
                        },
                        {
                            type: 'string',
                            enum: ['payconiq']
                        },
                        {
                            type: 'string',
                            enum: ['paysafecard']
                        },
                        {
                            type: 'string',
                            enum: ['p24']
                        },
                        {
                            type: 'string',
                            enum: ['przelewy24']
                        },
                        {
                            type: 'string',
                            enum: ['przelewy24p24']
                        },
                        {
                            type: 'string',
                            enum: ['satispay']
                        },
                        {
                            type: 'string',
                            enum: ['sepadebit']
                        },
                        {
                            type: 'string',
                            enum: ['sepaddmodelc']
                        },
                        {
                            type: 'string',
                            enum: ['sepaddmodela']
                        },
                        {
                            type: 'string',
                            enum: ['skrill']
                        },
                        {
                            type: 'string',
                            enum: ['todito']
                        },
                        {
                            type: 'string',
                            enum: ['tosspay']
                        },
                        {
                            type: 'string',
                            enum: ['touchngo']
                        },
                        {
                            type: 'string',
                            enum: ['trustly']
                        },
                        {
                            type: 'string',
                            enum: ['upi']
                        },
                        {
                            type: 'string',
                            enum: ['unionpay']
                        },
                        {
                            type: 'string',
                            enum: ['visa']
                        },
                        {
                            type: 'string',
                            enum: ['wechatpay']
                        },
                        {
                            type: 'string',
                            enum: ['zip']
                        },
                        {
                            type: 'string',
                            enum: ['zipus']
                        },
                        {
                            type: 'string',
                            enum: ['pbba']
                        },
                        {
                            type: 'string',
                            enum: ['paybybankapp']
                        },
                        {
                            type: 'string',
                            enum: ['paybybankapppbba']
                        },
                        {
                            type: 'string',
                            enum: ['payu']
                        },
                        {
                            type: 'string',
                            enum: ['klasha']
                        },
                        {
                            type: 'string',
                            enum: ['card']
                        },
                        {
                            type: 'string',
                            enum: ['banktransaction']
                        },
                        {
                            type: 'string',
                            enum: ['mobilemoney']
                        },
                        {
                            type: 'string',
                            enum: ['mpesa']
                        },
                        {
                            type: 'string',
                            enum: ['wemabank']
                        },
                        {
                            type: 'string',
                            enum: ['cardafrica']
                        },
                        {
                            type: 'string',
                            enum: ['afterpay']
                        },
                        {
                            type: 'string',
                            enum: ['klarna']
                        },
                        {
                            type: 'string',
                            enum: ['payovertimeklarna']
                        },
                        {
                            type: 'string',
                            enum: ['paylaterklarna']
                        },
                        {
                            type: 'string',
                            enum: ['paynowklarna']
                        },
                        {
                            type: 'string',
                            enum: ['banktransferklarna']
                        },
                        {
                            type: 'string',
                            enum: ['directdebitklarna']
                        },
                        {
                            type: 'string',
                            enum: ['upiinstore']
                        },
                        {
                            type: 'string',
                            enum: ['mbway']
                        },
                        {
                            type: 'string',
                            enum: ['thaibanks']
                        },
                        {
                            type: 'string',
                            enum: ['thaibanksapp']
                        },
                        {
                            type: 'string',
                            enum: ['skrilltap']
                        },
                        {
                            type: 'string',
                            enum: ['clearpay']
                        },
                        {
                            type: 'string',
                            enum: ['onlinebanking']
                        },
                        {
                            type: 'string',
                            enum: ['doku']
                        },
                        {
                            type: 'string',
                            enum: ['shoppepay']
                        },
                        {
                            type: 'string',
                            enum: ['shopeepay']
                        },
                        {
                            type: 'string',
                            enum: ['truemoney']
                        },
                        {
                            type: 'string',
                            enum: ['kbank']
                        },
                        {
                            type: 'string',
                            enum: ['kodd']
                        },
                        {
                            type: 'string',
                            enum: ['thaiqr']
                        },
                        {
                            type: 'string',
                            enum: ['cardus']
                        },
                        {
                            type: 'string',
                            enum: ['cardsus']
                        },
                        {
                            type: 'string',
                            enum: ['kakaopay']
                        },
                        {
                            type: 'string',
                            enum: ['tmn']
                        },
                        {
                            type: 'string',
                            enum: ['mpay']
                        },
                        {
                            type: 'string',
                            enum: ['rabbitlinepay']
                        },
                        {
                            type: 'string',
                            enum: ['boost']
                        },
                        {
                            type: 'string',
                            enum: ['bpi']
                        },
                        {
                            type: 'string',
                            enum: ['tng']
                        },
                        {
                            type: 'string',
                            enum: ['dana']
                        },
                        {
                            type: 'string',
                            enum: ['alipayhk']
                        },
                        {
                            type: 'string',
                            enum: ['gcash']
                        },
                        {
                            type: 'string',
                            enum: ['tsp']
                        },
                        {
                            type: 'string',
                            enum: ['tinaba']
                        },
                        {
                            type: 'string',
                            enum: ['kredivo']
                        },
                        {
                            type: 'string',
                            enum: ['naverpay']
                        },
                        {
                            type: 'string',
                            enum: ['kplus']
                        },
                        {
                            type: 'string',
                            enum: ['billease']
                        },
                        {
                            type: 'string',
                            enum: ['alipaycn']
                        },
                        {
                            type: 'string',
                            enum: ['creditcardupop']
                        },
                        {
                            type: 'string',
                            enum: ['alipayup']
                        },
                        {
                            type: 'string',
                            enum: ['upop']
                        },
                        {
                            type: 'string',
                            enum: ['wechatpayup']
                        },
                        {
                            type: 'string',
                            enum: ['qp']
                        },
                        {
                            type: 'string',
                            enum: ['creditcardvm']
                        }
                    ]
                },
                holderName: {
                    type: 'string'
                },
                firstName: {
                    type: 'string'
                },
                lastName: {
                    type: 'string'
                },
                shopperEmail: {
                    type: 'string'
                }
            },
            required: ['type']
        },
        productDetail: {
            description: '产品详细描述信息',
            type: 'string'
        },
        productId: {
            description: '产品 ID',
            type: 'string'
        },
        productName: {
            description: '产品名称',
            type: 'string'
        },
        reference: {
            description: '订单唯一参考号',
            type: 'string'
        },
        returnUrl: {
            format: 'uri',
            description: '支付完成后的回调 URL',
            type: 'string'
        },
        webhookUrl: {
            format: 'uri',
            description: '支付通知 Webhook URL',
            type: 'string'
        },
        browserInfo: {
            description: '浏览器终端信息',
            type: 'object',
            properties: {
                terminalType: {
                    description: '终端类型，例如 WEB, MOBILE',
                    type: 'string'
                }
            }
        },
        processingCurrency: {
            minLength: 3,
            maxLength: 3,
            description: '支付处理货币，符合 ISO 4217 货币代码',
            type: 'string'
        }
    },
    required: ['amount', 'countryCode', 'isExchange', 'merchantAccount', 'merchantId', 'origin', 'paymentMethod', 'productDetail', 'productId', 'productName', 'reference', 'returnUrl', 'webhookUrl', 'processingCurrency'],
    title: 'PaymentInputSchema'
} as const;

export const PaymentOrderOutputSchemaFastifySchema = {
    type: 'object',
    properties: {
        countryCode: {
            minLength: 2,
            maxLength: 2,
            default: 'CN',
            type: 'string'
        },
        productId: {
            maxLength: 128,
            default: 'default_product',
            type: 'string'
        },
        merchantId: {
            maxLength: 128,
            default: 'default_merchant',
            type: 'string'
        },
        origin: {
            format: 'uri',
            default: 'https://example.com',
            type: 'string'
        },
        productName: {
            maxLength: 128,
            default: 'Default Product',
            type: 'string'
        },
        productDetail: {
            maxLength: 256,
            default: 'Default Product Detail',
            type: 'string'
        },
        pspReference: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        reference: {
            maxLength: 128,
            default: 'default_reference',
            type: 'string'
        },
        returnUrl: {
            format: 'uri',
            default: 'https://example.com/return',
            type: 'string'
        },
        merchantAccount: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        webhookUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        PaymentMethod: {
            type: 'string'
        },
        version: {
            default: 1,
            type: 'integer'
        },
        isexchange: {
            type: 'boolean'
        },
        amount: {
            type: 'object',
            properties: {
                currency: {
                    type: 'string'
                },
                value: {
                    type: 'number'
                }
            },
            required: ['currency', 'value']
        },
        expiredAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: ['countryCode', 'productId', 'merchantId', 'origin', 'productName', 'productDetail', 'reference', 'returnUrl', 'version', 'isexchange', 'amount', 'expiredAt'],
    title: 'PaymentOrderOutputSchemaFastify'
} as const;

export const PaymentOrderDebugSchemaSchema = {
    type: 'object',
    properties: {
        amount: {
            minimum: 1,
            default: 100,
            description: '支付金额（整数，实际金额乘以 100，例如 200 USD 传入 20000）',
            type: 'integer'
        },
        currency: {
            default: 'USD',
            pattern: '^[A-Z]{3}$',
            description: '货币代码（3 个大写字母，例如 USD）',
            type: 'string'
        },
        holderName: {
            default: '',
            description: '持卡人姓名',
            type: 'string'
        },
        shopperEmail: {
            format: 'email',
            description: '购物者邮箱',
            type: 'string'
        },
        paymentType: {
            default: '',
            description: '支付方式（例如 alipaycn）',
            type: 'string'
        },
        merchantId: {
            pattern: '^[0-9]{1,19}$',
            default: '1',
            description: '商户 ID',
            type: 'string'
        }
    },
    required: ['amount', 'currency'],
    title: 'PaymentOrderDebugSchema'
} as const;
