// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as ClientOptions, TDataShape } from '@hey-api/client-fetch';
import type {
  GetApiHealthData,
  GetApiHealthResponse,
  GetAuditLogByIdData,
  GetAuditLogByIdResponse,
  GetAuditLogData,
  GetAuditLogResponse,
  GetAuditLogStatsOperationTypesData,
  GetAuditLogStatsOperationTypesResponse,
  GetAuditLogStatsRecentActivityData,
  GetAuditLogStatsRecentActivityResponse,
  GetCityCityListData,
  GetCityCityListResponse,
  GetDashboardCbdDistributionData,
  GetDashboardCbdDistributionResponse,
  GetDashboardData,
  GetDashboardRecentShopsData,
  GetDashboardRecentShopsResponse,
  GetDashboardResponse,
  GetDashboardShopTypeDistributionData,
  GetDashboardShopTypeDistributionResponse,
  GetData,
  GetHealthData,
  GetHealthResponse,
  GetPartByIdData,
  GetPartByIdResponse,
  GetPositionByIdData,
  GetPositionByIdResponse,
  GetResponse,
  GetShopByIdData,
  GetShopByIdResponse,
  GetShopListData,
  GetShopListResponse,
  GetShopListUnbindData,
  GetShopListUnbindResponse,
  GetSpaceByIdData,
  GetSpaceByIdResponse,
  PostCbdListData,
  PostCbdListResponse,
  PostDistrictListData,
  PostDistrictListResponse,
  PostPartAddData,
  PostPartAddResponse,
  PostPartDeleteData,
  PostPartDeleteResponse,
  PostPartListData,
  PostPartListResponse,
  PostPartUpdateData,
  PostPartUpdateResponse,
  PostPositionAddData,
  PostPositionAddResponse,
  PostPositionBindShopData,
  PostPositionBindShopResponse,
  PostPositionDeleteData,
  PostPositionDeleteResponse,
  PostPositionListData,
  PostPositionListResponse,
  PostPositionMarkData,
  PostPositionMarkResponse,
  PostPositionSetData,
  PostPositionSetResponse,
  PostPositionUpdateData,
  PostPositionUpdateResponse,
  PostShopAddData,
  PostShopAddResponse,
  PostShopDeleteData,
  PostShopDeleteResponse,
  PostShopUpdateData,
  PostShopUpdateResponse,
  PostSpaceAddData,
  PostSpaceAddResponse,
  PostSpaceDeleteData,
  PostSpaceDeleteResponse,
  PostSpaceListData,
  PostSpaceListResponse,
  PostSpaceUpdateData,
  PostSpaceUpdateResponse,
  PostSpaceUpdateStateData,
  PostSpaceUpdateStateResponse
} from './types.gen';
import { client as _heyApiClient } from './client.gen';
import {
  getAuditLogStatsRecentActivityResponseTransformer,
  getDashboardRecentShopsResponseTransformer
} from './transformers.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * /
 */
export const get = <ThrowOnError extends boolean = false>(options?: Options<GetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetResponse, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * /health
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetHealthResponse, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};

/**
 * /api/health
 */
export const getApiHealth = <ThrowOnError extends boolean = false>(options?: Options<GetApiHealthData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiHealthResponse, unknown, ThrowOnError>({
        url: '/api/health',
        ...options
    });
};

/**
 * /city/cityList
 * 获取城市列表
 */
export const getCityCityList = <ThrowOnError extends boolean = false>(options?: Options<GetCityCityListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCityCityListResponse, unknown, ThrowOnError>({
        url: '/city/cityList',
        ...options
    });
};

/**
 * /district/list
 * 获取区域列表
 */
export const postDistrictList = <ThrowOnError extends boolean = false>(options?: Options<PostDistrictListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostDistrictListResponse, unknown, ThrowOnError>({
        url: '/district/list',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /cbd/list
 * 获取商圈列表
 */
export const postCbdList = <ThrowOnError extends boolean = false>(options?: Options<PostCbdListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostCbdListResponse, unknown, ThrowOnError>({
        url: '/cbd/list',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /part/list
 * 获取物业小区列表
 */
export const postPartList = <ThrowOnError extends boolean = false>(options?: Options<PostPartListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostPartListResponse, unknown, ThrowOnError>({
        url: '/part/list',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /part/{id}
 * 获取物业小区详情
 */
export const getPartById = <ThrowOnError extends boolean = false>(options: Options<GetPartByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetPartByIdResponse, unknown, ThrowOnError>({
        url: '/part/{id}',
        ...options
    });
};

/**
 * /part/add
 * 新增分区
 */
export const postPartAdd = <ThrowOnError extends boolean = false>(options?: Options<PostPartAddData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostPartAddResponse, unknown, ThrowOnError>({
        url: '/part/add',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /part/update
 * 编辑分区
 */
export const postPartUpdate = <ThrowOnError extends boolean = false>(options?: Options<PostPartUpdateData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostPartUpdateResponse, unknown, ThrowOnError>({
        url: '/part/update',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /part/delete
 * 删除分区
 */
export const postPartDelete = <ThrowOnError extends boolean = false>(options?: Options<PostPartDeleteData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostPartDeleteResponse, unknown, ThrowOnError>({
        url: '/part/delete',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /position/list
 * 获取铺位列表
 */
export const postPositionList = <ThrowOnError extends boolean = false>(options?: Options<PostPositionListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostPositionListResponse, unknown, ThrowOnError>({
        url: '/position/list',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /position/{id}
 * 获取铺位详情
 */
export const getPositionById = <ThrowOnError extends boolean = false>(options: Options<GetPositionByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetPositionByIdResponse, unknown, ThrowOnError>({
        url: '/position/{id}',
        ...options
    });
};

/**
 * /position/add
 * 新增铺位
 */
export const postPositionAdd = <ThrowOnError extends boolean = false>(options?: Options<PostPositionAddData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostPositionAddResponse, unknown, ThrowOnError>({
        url: '/position/add',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /position/update
 * 编辑铺位
 */
export const postPositionUpdate = <ThrowOnError extends boolean = false>(options?: Options<PostPositionUpdateData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostPositionUpdateResponse, unknown, ThrowOnError>({
        url: '/position/update',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /position/delete
 * 删除铺位
 */
export const postPositionDelete = <ThrowOnError extends boolean = false>(options?: Options<PostPositionDeleteData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostPositionDeleteResponse, unknown, ThrowOnError>({
        url: '/position/delete',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /position/set
 * 置为空铺
 */
export const postPositionSet = <ThrowOnError extends boolean = false>(options?: Options<PostPositionSetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostPositionSetResponse, unknown, ThrowOnError>({
        url: '/position/set',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /position/bindShop
 * 关联新商家
 */
export const postPositionBindShop = <ThrowOnError extends boolean = false>(options?: Options<PostPositionBindShopData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostPositionBindShopResponse, unknown, ThrowOnError>({
        url: '/position/bindShop',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /position/mark
 * 快速标记铺位
 */
export const postPositionMark = <ThrowOnError extends boolean = false>(options?: Options<PostPositionMarkData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostPositionMarkResponse, unknown, ThrowOnError>({
        url: '/position/mark',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /shop/list
 * 商家列表
 */
export const getShopList = <ThrowOnError extends boolean = false>(options?: Options<GetShopListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetShopListResponse, unknown, ThrowOnError>({
        url: '/shop/list',
        ...options
    });
};

/**
 * /shop/listUnbind
 * 获取未关联商家列表
 */
export const getShopListUnbind = <ThrowOnError extends boolean = false>(options?: Options<GetShopListUnbindData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetShopListUnbindResponse, unknown, ThrowOnError>({
        url: '/shop/listUnbind',
        ...options
    });
};

/**
 * /shop/{id}
 * 商家详情
 */
export const getShopById = <ThrowOnError extends boolean = false>(options: Options<GetShopByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetShopByIdResponse, unknown, ThrowOnError>({
        url: '/shop/{id}',
        ...options
    });
};

/**
 * /shop/add
 * 新建商家
 */
export const postShopAdd = <ThrowOnError extends boolean = false>(options?: Options<PostShopAddData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostShopAddResponse, unknown, ThrowOnError>({
        url: '/shop/add',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /shop/update
 * 编辑商家
 */
export const postShopUpdate = <ThrowOnError extends boolean = false>(options?: Options<PostShopUpdateData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostShopUpdateResponse, unknown, ThrowOnError>({
        url: '/shop/update',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /shop/delete
 * 删除商家
 */
export const postShopDelete = <ThrowOnError extends boolean = false>(options?: Options<PostShopDeleteData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostShopDeleteResponse, unknown, ThrowOnError>({
        url: '/shop/delete',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /space/list
 * 获取广告位列表
 */
export const postSpaceList = <ThrowOnError extends boolean = false>(options?: Options<PostSpaceListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostSpaceListResponse, unknown, ThrowOnError>({
        url: '/space/list',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /space/{id}
 * 获取广告位详情
 */
export const getSpaceById = <ThrowOnError extends boolean = false>(options: Options<GetSpaceByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetSpaceByIdResponse, unknown, ThrowOnError>({
        url: '/space/{id}',
        ...options
    });
};

/**
 * /space/add
 * 新建广告位
 */
export const postSpaceAdd = <ThrowOnError extends boolean = false>(options?: Options<PostSpaceAddData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostSpaceAddResponse, unknown, ThrowOnError>({
        url: '/space/add',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /space/update
 * 编辑广告位
 */
export const postSpaceUpdate = <ThrowOnError extends boolean = false>(options?: Options<PostSpaceUpdateData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostSpaceUpdateResponse, unknown, ThrowOnError>({
        url: '/space/update',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /space/delete
 * 删除广告位
 */
export const postSpaceDelete = <ThrowOnError extends boolean = false>(options?: Options<PostSpaceDeleteData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostSpaceDeleteResponse, unknown, ThrowOnError>({
        url: '/space/delete',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /space/updateState
 * 启用/禁用广告位
 */
export const postSpaceUpdateState = <ThrowOnError extends boolean = false>(options?: Options<PostSpaceUpdateStateData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostSpaceUpdateStateResponse, unknown, ThrowOnError>({
        url: '/space/updateState',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * /dashboard/
 * 获取仪表盘统计数据
 */
export const getDashboard = <ThrowOnError extends boolean = false>(options?: Options<GetDashboardData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetDashboardResponse, unknown, ThrowOnError>({
        url: '/dashboard/',
        ...options
    });
};

/**
 * /dashboard/recent-shops
 * 获取最近添加的商家
 */
export const getDashboardRecentShops = <ThrowOnError extends boolean = false>(options?: Options<GetDashboardRecentShopsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetDashboardRecentShopsResponse, unknown, ThrowOnError>({
        responseTransformer: getDashboardRecentShopsResponseTransformer,
        url: '/dashboard/recent-shops',
        ...options
    });
};

/**
 * /dashboard/cbd-distribution
 * 获取商圈分布统计
 */
export const getDashboardCbdDistribution = <ThrowOnError extends boolean = false>(options?: Options<GetDashboardCbdDistributionData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetDashboardCbdDistributionResponse, unknown, ThrowOnError>({
        url: '/dashboard/cbd-distribution',
        ...options
    });
};

/**
 * /dashboard/shop-type-distribution
 * 获取商家类型分布
 */
export const getDashboardShopTypeDistribution = <ThrowOnError extends boolean = false>(options?: Options<GetDashboardShopTypeDistributionData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetDashboardShopTypeDistributionResponse, unknown, ThrowOnError>({
        url: '/dashboard/shop-type-distribution',
        ...options
    });
};

/**
 * /auditLog/
 * 获取审计日志列表
 */
export const getAuditLog = <ThrowOnError extends boolean = false>(options?: Options<GetAuditLogData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAuditLogResponse, unknown, ThrowOnError>({
        url: '/auditLog/',
        ...options
    });
};

/**
 * /auditLog/{id}
 * 获取审计日志详情
 */
export const getAuditLogById = <ThrowOnError extends boolean = false>(options: Options<GetAuditLogByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAuditLogByIdResponse, unknown, ThrowOnError>({
        url: '/auditLog/{id}',
        ...options
    });
};

/**
 * /auditLog/stats/operation-types
 * 获取操作类型统计
 */
export const getAuditLogStatsOperationTypes = <ThrowOnError extends boolean = false>(options?: Options<GetAuditLogStatsOperationTypesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAuditLogStatsOperationTypesResponse, unknown, ThrowOnError>({
        url: '/auditLog/stats/operation-types',
        ...options
    });
};

/**
 * /auditLog/stats/recent-activity
 * 获取近期操作记录统计
 */
export const getAuditLogStatsRecentActivity = <ThrowOnError extends boolean = false>(options?: Options<GetAuditLogStatsRecentActivityData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAuditLogStatsRecentActivityResponse, unknown, ThrowOnError>({
        responseTransformer: getAuditLogStatsRecentActivityResponseTransformer,
        url: '/auditLog/stats/recent-activity',
        ...options
    });
};
