// This file is auto-generated by @hey-api/openapi-ts

import { type Options, getHealth, getCityCityList, postDistrictList, postCbdList, postPartList, getPartById, postPartAdd, postPartUpdate, postPartDelete, postPositionList, getPositionById, postPositionAdd, postPositionUpdate, postPositionDelete, postPositionSet, postPositionBindShop, postPositionMark, getShopList, getShopListUnbind, getShopById, postShopAdd, postShopUpdate, postShopDelete, postSpaceList, getSpaceById, postSpaceAdd, postSpaceUpdate, postSpaceDelete, postSpaceUpdateState, getDashboard, getDashboardRecentShops, getDashboardCbdDistribution, getDashboardShopTypeDistribution, getAuditLog, getAuditLogById, getAuditLogStatsOperationTypes, getAuditLogStatsRecentActivity } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError, infiniteQueryOptions, type InfiniteData } from '@tanstack/react-query';
import type { GetHealthData, GetCityCityListData, PostDistrictListData, PostDistrictListResponse, PostCbdListData, PostCbdListResponse, PostPartListData, PostPartListResponse, GetPartByIdData, PostPartAddData, PostPartAddResponse, PostPartUpdateData, PostPartUpdateResponse, PostPartDeleteData, PostPartDeleteResponse, PostPositionListData, PostPositionListResponse, GetPositionByIdData, PostPositionAddData, PostPositionAddResponse, PostPositionUpdateData, PostPositionUpdateResponse, PostPositionDeleteData, PostPositionDeleteResponse, PostPositionSetData, PostPositionSetResponse, PostPositionBindShopData, PostPositionBindShopResponse, PostPositionMarkData, PostPositionMarkResponse, GetShopListData, GetShopListUnbindData, GetShopByIdData, PostShopAddData, PostShopAddResponse, PostShopUpdateData, PostShopUpdateResponse, PostShopDeleteData, PostShopDeleteResponse, PostSpaceListData, PostSpaceListResponse, GetSpaceByIdData, PostSpaceAddData, PostSpaceAddResponse, PostSpaceUpdateData, PostSpaceUpdateResponse, PostSpaceDeleteData, PostSpaceDeleteResponse, PostSpaceUpdateStateData, PostSpaceUpdateStateResponse, GetDashboardData, GetDashboardRecentShopsData, GetDashboardCbdDistributionData, GetDashboardShopTypeDistributionData, GetAuditLogData, GetAuditLogResponse, GetAuditLogByIdData, GetAuditLogStatsOperationTypesData, GetAuditLogStatsRecentActivityData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

export const getHealthOptions = (options?: Options<GetHealthData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getHealth({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getHealthQueryKey(options)
    });
};

export const getCityCityListQueryKey = (options?: Options<GetCityCityListData>) => createQueryKey('getCityCityList', options);

export const getCityCityListOptions = (options?: Options<GetCityCityListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCityCityList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCityCityListQueryKey(options)
    });
};

export const postDistrictListQueryKey = (options: Options<PostDistrictListData>) => createQueryKey('postDistrictList', options);

export const postDistrictListOptions = (options: Options<PostDistrictListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postDistrictList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postDistrictListQueryKey(options)
    });
};

export const postDistrictListMutation = (options?: Partial<Options<PostDistrictListData>>) => {
    const mutationOptions: UseMutationOptions<PostDistrictListResponse, DefaultError, Options<PostDistrictListData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postDistrictList({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postCbdListQueryKey = (options: Options<PostCbdListData>) => createQueryKey('postCbdList', options);

export const postCbdListOptions = (options: Options<PostCbdListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postCbdList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postCbdListQueryKey(options)
    });
};

export const postCbdListMutation = (options?: Partial<Options<PostCbdListData>>) => {
    const mutationOptions: UseMutationOptions<PostCbdListResponse, DefaultError, Options<PostCbdListData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postCbdList({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postPartListQueryKey = (options?: Options<PostPartListData>) => createQueryKey('postPartList', options);

export const postPartListOptions = (options?: Options<PostPartListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postPartList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postPartListQueryKey(options)
    });
};

export const postPartListMutation = (options?: Partial<Options<PostPartListData>>) => {
    const mutationOptions: UseMutationOptions<PostPartListResponse, DefaultError, Options<PostPartListData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postPartList({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPartByIdQueryKey = (options: Options<GetPartByIdData>) => createQueryKey('getPartById', options);

export const getPartByIdOptions = (options: Options<GetPartByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPartById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getPartByIdQueryKey(options)
    });
};

export const postPartAddQueryKey = (options: Options<PostPartAddData>) => createQueryKey('postPartAdd', options);

export const postPartAddOptions = (options: Options<PostPartAddData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postPartAdd({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postPartAddQueryKey(options)
    });
};

export const postPartAddMutation = (options?: Partial<Options<PostPartAddData>>) => {
    const mutationOptions: UseMutationOptions<PostPartAddResponse, DefaultError, Options<PostPartAddData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postPartAdd({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postPartUpdateQueryKey = (options: Options<PostPartUpdateData>) => createQueryKey('postPartUpdate', options);

export const postPartUpdateOptions = (options: Options<PostPartUpdateData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postPartUpdate({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postPartUpdateQueryKey(options)
    });
};

export const postPartUpdateMutation = (options?: Partial<Options<PostPartUpdateData>>) => {
    const mutationOptions: UseMutationOptions<PostPartUpdateResponse, DefaultError, Options<PostPartUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postPartUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postPartDeleteQueryKey = (options: Options<PostPartDeleteData>) => createQueryKey('postPartDelete', options);

export const postPartDeleteOptions = (options: Options<PostPartDeleteData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postPartDelete({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postPartDeleteQueryKey(options)
    });
};

export const postPartDeleteMutation = (options?: Partial<Options<PostPartDeleteData>>) => {
    const mutationOptions: UseMutationOptions<PostPartDeleteResponse, DefaultError, Options<PostPartDeleteData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postPartDelete({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postPositionListQueryKey = (options?: Options<PostPositionListData>) => createQueryKey('postPositionList', options);

export const postPositionListOptions = (options?: Options<PostPositionListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postPositionList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postPositionListQueryKey(options)
    });
};

export const postPositionListMutation = (options?: Partial<Options<PostPositionListData>>) => {
    const mutationOptions: UseMutationOptions<PostPositionListResponse, DefaultError, Options<PostPositionListData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postPositionList({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPositionByIdQueryKey = (options: Options<GetPositionByIdData>) => createQueryKey('getPositionById', options);

export const getPositionByIdOptions = (options: Options<GetPositionByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPositionById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getPositionByIdQueryKey(options)
    });
};

export const postPositionAddQueryKey = (options: Options<PostPositionAddData>) => createQueryKey('postPositionAdd', options);

export const postPositionAddOptions = (options: Options<PostPositionAddData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postPositionAdd({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postPositionAddQueryKey(options)
    });
};

export const postPositionAddMutation = (options?: Partial<Options<PostPositionAddData>>) => {
    const mutationOptions: UseMutationOptions<PostPositionAddResponse, DefaultError, Options<PostPositionAddData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postPositionAdd({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postPositionUpdateQueryKey = (options: Options<PostPositionUpdateData>) => createQueryKey('postPositionUpdate', options);

export const postPositionUpdateOptions = (options: Options<PostPositionUpdateData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postPositionUpdate({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postPositionUpdateQueryKey(options)
    });
};

export const postPositionUpdateMutation = (options?: Partial<Options<PostPositionUpdateData>>) => {
    const mutationOptions: UseMutationOptions<PostPositionUpdateResponse, DefaultError, Options<PostPositionUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postPositionUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postPositionDeleteQueryKey = (options: Options<PostPositionDeleteData>) => createQueryKey('postPositionDelete', options);

export const postPositionDeleteOptions = (options: Options<PostPositionDeleteData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postPositionDelete({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postPositionDeleteQueryKey(options)
    });
};

export const postPositionDeleteMutation = (options?: Partial<Options<PostPositionDeleteData>>) => {
    const mutationOptions: UseMutationOptions<PostPositionDeleteResponse, DefaultError, Options<PostPositionDeleteData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postPositionDelete({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postPositionSetQueryKey = (options: Options<PostPositionSetData>) => createQueryKey('postPositionSet', options);

export const postPositionSetOptions = (options: Options<PostPositionSetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postPositionSet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postPositionSetQueryKey(options)
    });
};

export const postPositionSetMutation = (options?: Partial<Options<PostPositionSetData>>) => {
    const mutationOptions: UseMutationOptions<PostPositionSetResponse, DefaultError, Options<PostPositionSetData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postPositionSet({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postPositionBindShopQueryKey = (options: Options<PostPositionBindShopData>) => createQueryKey('postPositionBindShop', options);

export const postPositionBindShopOptions = (options: Options<PostPositionBindShopData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postPositionBindShop({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postPositionBindShopQueryKey(options)
    });
};

export const postPositionBindShopMutation = (options?: Partial<Options<PostPositionBindShopData>>) => {
    const mutationOptions: UseMutationOptions<PostPositionBindShopResponse, DefaultError, Options<PostPositionBindShopData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postPositionBindShop({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postPositionMarkQueryKey = (options: Options<PostPositionMarkData>) => createQueryKey('postPositionMark', options);

export const postPositionMarkOptions = (options: Options<PostPositionMarkData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postPositionMark({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postPositionMarkQueryKey(options)
    });
};

export const postPositionMarkMutation = (options?: Partial<Options<PostPositionMarkData>>) => {
    const mutationOptions: UseMutationOptions<PostPositionMarkResponse, DefaultError, Options<PostPositionMarkData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postPositionMark({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getShopListQueryKey = (options?: Options<GetShopListData>) => createQueryKey('getShopList', options);

export const getShopListOptions = (options?: Options<GetShopListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getShopList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getShopListQueryKey(options)
    });
};

export const getShopListUnbindQueryKey = (options?: Options<GetShopListUnbindData>) => createQueryKey('getShopListUnbind', options);

export const getShopListUnbindOptions = (options?: Options<GetShopListUnbindData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getShopListUnbind({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getShopListUnbindQueryKey(options)
    });
};

export const getShopByIdQueryKey = (options: Options<GetShopByIdData>) => createQueryKey('getShopById', options);

export const getShopByIdOptions = (options: Options<GetShopByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getShopById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getShopByIdQueryKey(options)
    });
};

export const postShopAddQueryKey = (options: Options<PostShopAddData>) => createQueryKey('postShopAdd', options);

export const postShopAddOptions = (options: Options<PostShopAddData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postShopAdd({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postShopAddQueryKey(options)
    });
};

export const postShopAddMutation = (options?: Partial<Options<PostShopAddData>>) => {
    const mutationOptions: UseMutationOptions<PostShopAddResponse, DefaultError, Options<PostShopAddData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postShopAdd({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postShopUpdateQueryKey = (options: Options<PostShopUpdateData>) => createQueryKey('postShopUpdate', options);

export const postShopUpdateOptions = (options: Options<PostShopUpdateData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postShopUpdate({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postShopUpdateQueryKey(options)
    });
};

export const postShopUpdateMutation = (options?: Partial<Options<PostShopUpdateData>>) => {
    const mutationOptions: UseMutationOptions<PostShopUpdateResponse, DefaultError, Options<PostShopUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postShopUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postShopDeleteQueryKey = (options: Options<PostShopDeleteData>) => createQueryKey('postShopDelete', options);

export const postShopDeleteOptions = (options: Options<PostShopDeleteData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postShopDelete({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postShopDeleteQueryKey(options)
    });
};

export const postShopDeleteMutation = (options?: Partial<Options<PostShopDeleteData>>) => {
    const mutationOptions: UseMutationOptions<PostShopDeleteResponse, DefaultError, Options<PostShopDeleteData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postShopDelete({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postSpaceListQueryKey = (options: Options<PostSpaceListData>) => createQueryKey('postSpaceList', options);

export const postSpaceListOptions = (options: Options<PostSpaceListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postSpaceList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postSpaceListQueryKey(options)
    });
};

export const postSpaceListMutation = (options?: Partial<Options<PostSpaceListData>>) => {
    const mutationOptions: UseMutationOptions<PostSpaceListResponse, DefaultError, Options<PostSpaceListData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postSpaceList({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSpaceByIdQueryKey = (options: Options<GetSpaceByIdData>) => createQueryKey('getSpaceById', options);

export const getSpaceByIdOptions = (options: Options<GetSpaceByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSpaceById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getSpaceByIdQueryKey(options)
    });
};

export const postSpaceAddQueryKey = (options: Options<PostSpaceAddData>) => createQueryKey('postSpaceAdd', options);

export const postSpaceAddOptions = (options: Options<PostSpaceAddData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postSpaceAdd({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postSpaceAddQueryKey(options)
    });
};

export const postSpaceAddMutation = (options?: Partial<Options<PostSpaceAddData>>) => {
    const mutationOptions: UseMutationOptions<PostSpaceAddResponse, DefaultError, Options<PostSpaceAddData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postSpaceAdd({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postSpaceUpdateQueryKey = (options: Options<PostSpaceUpdateData>) => createQueryKey('postSpaceUpdate', options);

export const postSpaceUpdateOptions = (options: Options<PostSpaceUpdateData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postSpaceUpdate({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postSpaceUpdateQueryKey(options)
    });
};

export const postSpaceUpdateMutation = (options?: Partial<Options<PostSpaceUpdateData>>) => {
    const mutationOptions: UseMutationOptions<PostSpaceUpdateResponse, DefaultError, Options<PostSpaceUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postSpaceUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postSpaceDeleteQueryKey = (options: Options<PostSpaceDeleteData>) => createQueryKey('postSpaceDelete', options);

export const postSpaceDeleteOptions = (options: Options<PostSpaceDeleteData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postSpaceDelete({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postSpaceDeleteQueryKey(options)
    });
};

export const postSpaceDeleteMutation = (options?: Partial<Options<PostSpaceDeleteData>>) => {
    const mutationOptions: UseMutationOptions<PostSpaceDeleteResponse, DefaultError, Options<PostSpaceDeleteData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postSpaceDelete({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postSpaceUpdateStateQueryKey = (options: Options<PostSpaceUpdateStateData>) => createQueryKey('postSpaceUpdateState', options);

export const postSpaceUpdateStateOptions = (options: Options<PostSpaceUpdateStateData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postSpaceUpdateState({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postSpaceUpdateStateQueryKey(options)
    });
};

export const postSpaceUpdateStateMutation = (options?: Partial<Options<PostSpaceUpdateStateData>>) => {
    const mutationOptions: UseMutationOptions<PostSpaceUpdateStateResponse, DefaultError, Options<PostSpaceUpdateStateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postSpaceUpdateState({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getDashboardQueryKey = (options?: Options<GetDashboardData>) => createQueryKey('getDashboard', options);

export const getDashboardOptions = (options?: Options<GetDashboardData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getDashboard({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getDashboardQueryKey(options)
    });
};

export const getDashboardRecentShopsQueryKey = (options?: Options<GetDashboardRecentShopsData>) => createQueryKey('getDashboardRecentShops', options);

export const getDashboardRecentShopsOptions = (options?: Options<GetDashboardRecentShopsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getDashboardRecentShops({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getDashboardRecentShopsQueryKey(options)
    });
};

export const getDashboardCbdDistributionQueryKey = (options?: Options<GetDashboardCbdDistributionData>) => createQueryKey('getDashboardCbdDistribution', options);

export const getDashboardCbdDistributionOptions = (options?: Options<GetDashboardCbdDistributionData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getDashboardCbdDistribution({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getDashboardCbdDistributionQueryKey(options)
    });
};

export const getDashboardShopTypeDistributionQueryKey = (options?: Options<GetDashboardShopTypeDistributionData>) => createQueryKey('getDashboardShopTypeDistribution', options);

export const getDashboardShopTypeDistributionOptions = (options?: Options<GetDashboardShopTypeDistributionData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getDashboardShopTypeDistribution({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getDashboardShopTypeDistributionQueryKey(options)
    });
};

export const getAuditLogQueryKey = (options?: Options<GetAuditLogData>) => createQueryKey('getAuditLog', options);

export const getAuditLogOptions = (options?: Options<GetAuditLogData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAuditLog({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAuditLogQueryKey(options)
    });
};

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = queryKey[0];
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getAuditLogInfiniteQueryKey = (options?: Options<GetAuditLogData>): QueryKey<Options<GetAuditLogData>> => createQueryKey('getAuditLog', options, true);

export const getAuditLogInfiniteOptions = (options?: Options<GetAuditLogData>) => {
    return infiniteQueryOptions<GetAuditLogResponse, DefaultError, InfiniteData<GetAuditLogResponse>, QueryKey<Options<GetAuditLogData>>, number | Pick<QueryKey<Options<GetAuditLogData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetAuditLogData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getAuditLog({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAuditLogInfiniteQueryKey(options)
    });
};

export const getAuditLogByIdQueryKey = (options: Options<GetAuditLogByIdData>) => createQueryKey('getAuditLogById', options);

export const getAuditLogByIdOptions = (options: Options<GetAuditLogByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAuditLogById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAuditLogByIdQueryKey(options)
    });
};

export const getAuditLogStatsOperationTypesQueryKey = (options?: Options<GetAuditLogStatsOperationTypesData>) => createQueryKey('getAuditLogStatsOperationTypes', options);

export const getAuditLogStatsOperationTypesOptions = (options?: Options<GetAuditLogStatsOperationTypesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAuditLogStatsOperationTypes({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAuditLogStatsOperationTypesQueryKey(options)
    });
};

export const getAuditLogStatsRecentActivityQueryKey = (options?: Options<GetAuditLogStatsRecentActivityData>) => createQueryKey('getAuditLogStatsRecentActivity', options);

export const getAuditLogStatsRecentActivityOptions = (options?: Options<GetAuditLogStatsRecentActivityData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAuditLogStatsRecentActivity({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAuditLogStatsRecentActivityQueryKey(options)
    });
};