// This file is auto-generated by @hey-api/openapi-ts

export const cbdResponseSchemaSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        addr: {
            type: ['string', 'null']
        }
    },
    required: ['id', 'name', 'addr'],
    additionalProperties: false,
    title: 'cbdResponseSchema'
} as const;

export const cityResponseSchemaSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        }
    },
    required: ['id', 'name'],
    additionalProperties: false,
    title: 'cityResponseSchema'
} as const;

export const districtResponseSchemaSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        }
    },
    required: ['id', 'name'],
    additionalProperties: false,
    title: 'districtResponseSchema'
} as const;

export const partResponseSchemaSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        sequence: {
            type: 'number'
        },
        total_space: {
            type: 'number'
        }
    },
    required: ['id', 'name', 'sequence', 'total_space'],
    additionalProperties: false,
    title: 'partResponseSchema'
} as const;

export const shopResponseSchemaSchema = {
    type: 'object',
    properties: {
        shopId: {
            type: 'string'
        },
        shop_no: {
            type: 'string'
        },
        trademark: {
            type: 'string'
        },
        branch: {
            type: ['string', 'null']
        },
        total_space: {
            type: 'number'
        },
        put_space: {
            type: 'number'
        },
        price_base: {
            type: 'number'
        },
        verified: {
            type: 'boolean'
        },
        displayed: {
            type: 'boolean'
        },
        type: {
            type: 'string'
        },
        type_tag: {
            type: ['string', 'null']
        },
        photo: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        remark: {
            type: ['string', 'null']
        },
        business_hours: {
            type: 'array',
            items: {
                type: 'number'
            }
        },
        total_area: {
            type: ['number', 'null']
        },
        customer_area: {
            type: ['number', 'null']
        },
        clerk_count: {
            type: ['number', 'null']
        },
        business_type: {
            type: 'string'
        },
        duration: {
            type: 'string'
        },
        sex: {
            type: 'string'
        },
        age: {
            type: 'array',
            items: {
                type: 'number'
            }
        },
        id_tag: {
            type: ['string', 'null']
        },
        sign_photo: {
            type: ['string', 'null']
        },
        contact_type: {
            type: 'string'
        }
    },
    required: ['shopId', 'shop_no', 'trademark', 'branch', 'total_space', 'put_space', 'price_base', 'verified', 'displayed', 'type', 'type_tag', 'photo', 'remark', 'business_hours', 'total_area', 'customer_area', 'clerk_count', 'business_type', 'duration', 'sex', 'age', 'id_tag', 'sign_photo', 'contact_type'],
    additionalProperties: false,
    title: 'shopResponseSchema'
} as const;

export const spaceResponseSchemaSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        type: {
            type: 'string'
        },
        setting: {
            type: 'object',
            additionalProperties: {}
        },
        count: {
            type: 'number'
        },
        state: {
            type: 'string'
        },
        photo: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        priceFactor: {
            type: 'number',
            exclusiveMinimum: 0,
            default: 1,
            description: '价格因子'
        },
        updatedAt: {
            type: 'string'
        }
    },
    required: ['id', 'type', 'setting', 'count', 'state', 'photo', 'updatedAt'],
    additionalProperties: false,
    title: 'spaceResponseSchema'
} as const;

export const PositionSchema = {
    type: 'object',
    properties: {
        positionId: {
            type: 'string'
        },
        position_no: {
            type: 'string'
        },
        shopId: {
            type: ['string', 'null']
        },
        shop_no: {
            type: ['string', 'null']
        },
        total_space: {
            type: 'number'
        },
        put_space: {
            type: 'number'
        },
        price_base: {
            type: 'number'
        },
        verified: {
            type: 'boolean'
        },
        displayed: {
            type: 'boolean'
        },
        type: {
            type: ['string', 'null']
        },
        type_tag: {
            type: ['string', 'null']
        },
        photo: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        remark: {
            type: ['string', 'null']
        },
        business_hours: {
            type: 'array',
            items: {
                type: 'number'
            }
        }
    },
    required: ['positionId', 'position_no', 'shopId', 'shop_no', 'total_space', 'put_space', 'price_base', 'verified', 'displayed', 'type', 'type_tag', 'photo', 'remark', 'business_hours'],
    additionalProperties: false,
    title: 'Position'
} as const;

export const AuditLogSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        operationType: {
            type: 'string'
        },
        targetType: {
            type: 'string'
        },
        targetId: {
            type: 'string'
        },
        targetName: {
            type: 'string'
        },
        content: {
            type: 'string'
        },
        operatorId: {
            type: 'string'
        },
        operatorName: {
            type: 'string'
        },
        operationTime: {
            type: 'string'
        },
        details: {
            type: 'object',
            additionalProperties: {}
        },
        ipAddress: {
            type: ['string', 'null']
        },
        userAgent: {
            type: ['string', 'null']
        }
    },
    required: ['id', 'operationType', 'targetType', 'targetId', 'targetName', 'content', 'operatorId', 'operatorName', 'operationTime', 'ipAddress', 'userAgent'],
    additionalProperties: false,
    title: 'AuditLog'
} as const;