// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetHealthData, GetCityCityListData, GetCityCityListResponse, PostDistrictListData, PostDistrictListResponse, PostCbdListData, PostCbdListResponse, PostPartListData, PostPartListResponse, PostPartAddData, PostPartAddResponse, PostPartUpdateData, PostPartUpdateResponse, PostPartDeleteData, PostPartDeleteResponse, PostPositionListData, PostPositionListResponse, PostPositionAddData, PostPositionAddResponse, PostPositionUpdateData, PostPositionUpdateResponse, PostPositionDeleteData, PostPositionDeleteResponse, PostPositionSetData, PostPositionSetResponse, PostPositionBindShopData, PostPositionBindShopResponse, PostPositionMarkData, PostPositionMarkResponse, GetShopListUnbindData, GetShopListUnbindResponse, PostShopAddData, PostShopAddResponse, PostShopUpdateData, PostShopUpdateResponse, PostShopDeleteData, PostShopDeleteResponse, PostSpaceListData, PostSpaceListResponse, GetSpaceByIdData, PostSpaceAddData, PostSpaceAddResponse, PostSpaceUpdateData, PostSpaceUpdateResponse, PostSpaceDeleteData, PostSpaceDeleteResponse, PostSpaceUpdateStateData, PostSpaceUpdateStateResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};

/**
 * 获取城市列表
 */
export const getCityCityList = <ThrowOnError extends boolean = false>(options?: Options<GetCityCityListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCityCityListResponse, unknown, ThrowOnError>({
        url: '/city/cityList',
        ...options
    });
};

/**
 * 获取区域列表
 */
export const postDistrictList = <ThrowOnError extends boolean = false>(options: Options<PostDistrictListData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostDistrictListResponse, unknown, ThrowOnError>({
        url: '/district/list',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 获取商圈列表
 */
export const postCbdList = <ThrowOnError extends boolean = false>(options: Options<PostCbdListData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostCbdListResponse, unknown, ThrowOnError>({
        url: '/cbd/list',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 获取物业分区列表
 */
export const postPartList = <ThrowOnError extends boolean = false>(options?: Options<PostPartListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostPartListResponse, unknown, ThrowOnError>({
        url: '/part/list',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 新增分区
 */
export const postPartAdd = <ThrowOnError extends boolean = false>(options: Options<PostPartAddData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostPartAddResponse, unknown, ThrowOnError>({
        url: '/part/add',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 编辑分区
 */
export const postPartUpdate = <ThrowOnError extends boolean = false>(options: Options<PostPartUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostPartUpdateResponse, unknown, ThrowOnError>({
        url: '/part/update',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 删除分区
 */
export const postPartDelete = <ThrowOnError extends boolean = false>(options: Options<PostPartDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostPartDeleteResponse, unknown, ThrowOnError>({
        url: '/part/delete',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 获取铺位列表
 */
export const postPositionList = <ThrowOnError extends boolean = false>(options?: Options<PostPositionListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostPositionListResponse, unknown, ThrowOnError>({
        url: '/position/list',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 新增铺位
 */
export const postPositionAdd = <ThrowOnError extends boolean = false>(options: Options<PostPositionAddData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostPositionAddResponse, unknown, ThrowOnError>({
        url: '/position/add',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 编辑铺位
 */
export const postPositionUpdate = <ThrowOnError extends boolean = false>(options: Options<PostPositionUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostPositionUpdateResponse, unknown, ThrowOnError>({
        url: '/position/update',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 删除铺位
 */
export const postPositionDelete = <ThrowOnError extends boolean = false>(options: Options<PostPositionDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostPositionDeleteResponse, unknown, ThrowOnError>({
        url: '/position/delete',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 置为空铺
 */
export const postPositionSet = <ThrowOnError extends boolean = false>(options: Options<PostPositionSetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostPositionSetResponse, unknown, ThrowOnError>({
        url: '/position/set',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 关联新店铺
 */
export const postPositionBindShop = <ThrowOnError extends boolean = false>(options: Options<PostPositionBindShopData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostPositionBindShopResponse, unknown, ThrowOnError>({
        url: '/position/bindShop',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 快速标记铺位
 */
export const postPositionMark = <ThrowOnError extends boolean = false>(options: Options<PostPositionMarkData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostPositionMarkResponse, unknown, ThrowOnError>({
        url: '/position/mark',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 获取未关联店铺列表
 */
export const getShopListUnbind = <ThrowOnError extends boolean = false>(options?: Options<GetShopListUnbindData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetShopListUnbindResponse, unknown, ThrowOnError>({
        url: '/shop/listUnbind',
        ...options
    });
};

/**
 * 新建店铺
 */
export const postShopAdd = <ThrowOnError extends boolean = false>(options: Options<PostShopAddData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostShopAddResponse, unknown, ThrowOnError>({
        url: '/shop/add',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 编辑店铺
 */
export const postShopUpdate = <ThrowOnError extends boolean = false>(options: Options<PostShopUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostShopUpdateResponse, unknown, ThrowOnError>({
        url: '/shop/update',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 删除店铺
 */
export const postShopDelete = <ThrowOnError extends boolean = false>(options: Options<PostShopDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostShopDeleteResponse, unknown, ThrowOnError>({
        url: '/shop/delete',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 获取广告位列表
 */
export const postSpaceList = <ThrowOnError extends boolean = false>(options: Options<PostSpaceListData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostSpaceListResponse, unknown, ThrowOnError>({
        url: '/space/list',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getSpaceById = <ThrowOnError extends boolean = false>(options: Options<GetSpaceByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/space/{id}',
        ...options
    });
};

/**
 * 新建广告位
 */
export const postSpaceAdd = <ThrowOnError extends boolean = false>(options: Options<PostSpaceAddData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostSpaceAddResponse, unknown, ThrowOnError>({
        url: '/space/add',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 编辑广告位
 */
export const postSpaceUpdate = <ThrowOnError extends boolean = false>(options: Options<PostSpaceUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostSpaceUpdateResponse, unknown, ThrowOnError>({
        url: '/space/update',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 删除广告位
 */
export const postSpaceDelete = <ThrowOnError extends boolean = false>(options: Options<PostSpaceDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostSpaceDeleteResponse, unknown, ThrowOnError>({
        url: '/space/delete',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * 启用/禁用广告位
 */
export const postSpaceUpdateState = <ThrowOnError extends boolean = false>(options: Options<PostSpaceUpdateStateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostSpaceUpdateStateResponse, unknown, ThrowOnError>({
        url: '/space/updateState',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};