// This file is auto-generated by @hey-api/openapi-ts

export type CbdResponseSchema = {
    id: string;
    name: string;
    addr: unknown;
};

export type CityResponseSchema = {
    id: string;
    name: string;
};

export type DistrictResponseSchema = {
    id: string;
    name: string;
};

export type PartResponseSchema = {
    id: string;
    name: string;
    sequence: number;
    total_space: number;
};

export type ShopResponseSchema = {
    shopId: string;
    shop_no: string;
    trademark: string;
    branch: unknown;
    total_space: number;
    put_space: number;
    price_base: number;
    verified: boolean;
    displayed: boolean;
    type: string;
    type_tag: unknown;
    photo: Array<string>;
    remark: unknown;
    business_hours: Array<number>;
    total_area: unknown;
    customer_area: unknown;
    clerk_count: unknown;
    business_type: string;
    duration: string;
    sex: string;
    age: Array<number>;
    id_tag: unknown;
    sign_photo: unknown;
    contact_type: string;
};

export type SpaceResponseSchema = {
    id: string;
    type: string;
    setting: {};
    count: number;
    state: string;
    photo: Array<string>;
    /**
     * 价格因子
     */
    priceFactor?: number;
    updatedAt: string;
};

export type Position = {
    positionId: string;
    position_no: string;
    shopId: unknown;
    shop_no: unknown;
    total_space: number;
    put_space: number;
    price_base: number;
    verified: boolean;
    displayed: boolean;
    type: unknown;
    type_tag: unknown;
    photo: Array<string>;
    remark: unknown;
    business_hours: Array<number>;
};

export type AuditLog = {
    id: string;
    operationType: string;
    targetType: string;
    targetId: string;
    targetName: string;
    content: string;
    operatorId: string;
    operatorName: string;
    operationTime: string;
    details?: {};
    ipAddress: unknown;
    userAgent: unknown;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetCityCityListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/city/cityList';
};

export type GetCityCityListResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            list: Array<{
                id: string;
                name: string;
            }>;
        };
    };
};

export type GetCityCityListResponse = GetCityCityListResponses[keyof GetCityCityListResponses];

export type PostDistrictListData = {
    body: {
        /**
         * 城市ID
         */
        parentId: string;
    };
    path?: never;
    query?: never;
    url: '/district/list';
};

export type PostDistrictListResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            list: Array<{
                id: string;
                name: string;
            }>;
        };
    };
};

export type PostDistrictListResponse = PostDistrictListResponses[keyof PostDistrictListResponses];

export type PostCbdListData = {
    body: {
        /**
         * 行政区划ID
         */
        districtId: string;
    };
    path?: never;
    query?: never;
    url: '/cbd/list';
};

export type PostCbdListResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            list: Array<{
                id: string;
                name: string;
                addr: unknown;
            }>;
        };
    };
};

export type PostCbdListResponse = PostCbdListResponses[keyof PostCbdListResponses];

export type PostPartListData = {
    body?: {
        /**
         * 商圈ID
         */
        cbdId?: string;
    };
    path?: never;
    query?: never;
    url: '/part/list';
};

export type PostPartListResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            list: Array<{
                id: string;
                name: string;
                sequence: number;
                total_space: number;
            }>;
        };
    };
};

export type PostPartListResponse = PostPartListResponses[keyof PostPartListResponses];

export type GetPartByIdData = {
    body?: never;
    path: {
        /**
         * 分区ID
         */
        id: string;
    };
    query?: never;
    url: '/part/{id}';
};

export type GetPartByIdResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            id: string;
            name: string;
            sequence: number;
            total_space: number;
        };
    };
};

export type GetPartByIdResponse = GetPartByIdResponses[keyof GetPartByIdResponses];

export type PostPartAddData = {
    body: {
        /**
         * 商圈ID
         */
        cbdId: string;
        /**
         * 分区名称
         */
        name: string;
        /**
         * 排序值
         */
        sequence: number;
    };
    path?: never;
    query?: never;
    url: '/part/add';
};

export type PostPartAddResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: unknown;
    };
};

export type PostPartAddResponse = PostPartAddResponses[keyof PostPartAddResponses];

export type PostPartUpdateData = {
    body: {
        /**
         * 分区ID
         */
        id: string;
        /**
         * 分区名称
         */
        name: string;
    };
    path?: never;
    query?: never;
    url: '/part/update';
};

export type PostPartUpdateResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: unknown;
    };
};

export type PostPartUpdateResponse = PostPartUpdateResponses[keyof PostPartUpdateResponses];

export type PostPartDeleteData = {
    body: {
        /**
         * 分区ID
         */
        id: string;
    };
    path?: never;
    query?: never;
    url: '/part/delete';
};

export type PostPartDeleteResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: unknown;
    };
};

export type PostPartDeleteResponse = PostPartDeleteResponses[keyof PostPartDeleteResponses];

export type PostPositionListData = {
    body?: {
        /**
         * 分区ID
         */
        partId?: string;
    };
    path?: never;
    query?: never;
    url: '/position/list';
};

export type PostPositionListResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            list: Array<{
                positionId: string;
                position_no: string;
                shopId: unknown;
                shop_no: unknown;
                total_space: number;
                put_space: number;
                price_base: number;
                verified: boolean;
                displayed: boolean;
                type: unknown;
                type_tag: unknown;
                photo: Array<string>;
                remark: unknown;
                business_hours: Array<number>;
            }>;
        };
    };
};

export type PostPositionListResponse = PostPositionListResponses[keyof PostPositionListResponses];

export type GetPositionByIdData = {
    body?: never;
    path: {
        /**
         * 铺位ID
         */
        id: string;
    };
    query?: never;
    url: '/position/{id}';
};

export type GetPositionByIdResponses = {
    /**
     * 成功响应
     */
    201: {
        code?: number;
        data?: {
            positionId: string;
            position_no: string;
            shopId: unknown;
            shop_no: unknown;
            total_space: number;
            put_space: number;
            price_base: number;
            verified: boolean;
            displayed: boolean;
            type: unknown;
            type_tag: unknown;
            photo: Array<string>;
            remark: unknown;
            business_hours: Array<number>;
        };
    };
};

export type GetPositionByIdResponse = GetPositionByIdResponses[keyof GetPositionByIdResponses];

export type PostPositionAddData = {
    body: {
        /**
         * 商圈ID
         */
        cbdId: string;
        /**
         * 分区ID
         */
        partId: string;
        /**
         * 铺位编号
         */
        no: string;
    };
    path?: never;
    query?: never;
    url: '/position/add';
};

export type PostPositionAddResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: unknown;
    };
};

export type PostPositionAddResponse = PostPositionAddResponses[keyof PostPositionAddResponses];

export type PostPositionUpdateData = {
    body: {
        /**
         * 铺位ID
         */
        id: string;
        /**
         * 铺位编号
         */
        no: string;
    };
    path?: never;
    query?: never;
    url: '/position/update';
};

export type PostPositionUpdateResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: unknown;
    };
};

export type PostPositionUpdateResponse = PostPositionUpdateResponses[keyof PostPositionUpdateResponses];

export type PostPositionDeleteData = {
    body: {
        /**
         * 铺位ID
         */
        id: string;
    };
    path?: never;
    query?: never;
    url: '/position/delete';
};

export type PostPositionDeleteResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: unknown;
    };
};

export type PostPositionDeleteResponse = PostPositionDeleteResponses[keyof PostPositionDeleteResponses];

export type PostPositionSetData = {
    body: {
        /**
         * 铺位ID
         */
        id: string;
    };
    path?: never;
    query?: never;
    url: '/position/set';
};

export type PostPositionSetResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: unknown;
    };
};

export type PostPositionSetResponse = PostPositionSetResponses[keyof PostPositionSetResponses];

export type PostPositionBindShopData = {
    body: {
        /**
         * 铺位ID
         */
        id: string;
        /**
         * 店铺ID
         */
        shopId: string;
    };
    path?: never;
    query?: never;
    url: '/position/bindShop';
};

export type PostPositionBindShopResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: unknown;
    };
};

export type PostPositionBindShopResponse = PostPositionBindShopResponses[keyof PostPositionBindShopResponses];

export type PostPositionMarkData = {
    body: {
        /**
         * 铺位ID
         */
        id: string;
        /**
         * 标记内容
         */
        remark: string;
    };
    path?: never;
    query?: never;
    url: '/position/mark';
};

export type PostPositionMarkResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: unknown;
    };
};

export type PostPositionMarkResponse = PostPositionMarkResponses[keyof PostPositionMarkResponses];

export type GetShopListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/shop/list';
};

export type GetShopListResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            list: Array<{
                shopId: string;
                shop_no: string;
                trademark: string;
                branch: unknown;
                total_space: number;
                put_space: number;
                price_base: number;
                verified: boolean;
                displayed: boolean;
                type: string;
                type_tag: unknown;
                photo: Array<string>;
                remark: unknown;
                business_hours: Array<number>;
                total_area: unknown;
                customer_area: unknown;
                clerk_count: unknown;
                business_type: string;
                duration: string;
                sex: string;
                age: Array<number>;
                id_tag: unknown;
                sign_photo: unknown;
                contact_type: string;
            }>;
        };
    };
};

export type GetShopListResponse = GetShopListResponses[keyof GetShopListResponses];

export type GetShopListUnbindData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/shop/listUnbind';
};

export type GetShopListUnbindResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            list: Array<{
                shopId: string;
                shop_no: string;
                trademark: string;
                branch: unknown;
                total_space: number;
                put_space: number;
                price_base: number;
                verified: boolean;
                displayed: boolean;
                type: string;
                type_tag: unknown;
                photo: Array<string>;
                remark: unknown;
                business_hours: Array<number>;
                total_area: unknown;
                customer_area: unknown;
                clerk_count: unknown;
                business_type: string;
                duration: string;
                sex: string;
                age: Array<number>;
                id_tag: unknown;
                sign_photo: unknown;
                contact_type: string;
            }>;
        };
    };
};

export type GetShopListUnbindResponse = GetShopListUnbindResponses[keyof GetShopListUnbindResponses];

export type GetShopByIdData = {
    body?: never;
    path: {
        /**
         * 店铺ID
         */
        id: string;
    };
    query?: never;
    url: '/shop/{id}';
};

export type GetShopByIdResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            shopId: string;
            shop_no: string;
            trademark: string;
            branch: unknown;
            total_space: number;
            put_space: number;
            price_base: number;
            verified: boolean;
            displayed: boolean;
            type: string;
            type_tag: unknown;
            photo: Array<string>;
            remark: unknown;
            business_hours: Array<number>;
            total_area: unknown;
            customer_area: unknown;
            clerk_count: unknown;
            business_type: string;
            duration: string;
            sex: string;
            age: Array<number>;
            id_tag: unknown;
            sign_photo: unknown;
            contact_type: string;
        };
    };
};

export type GetShopByIdResponse = GetShopByIdResponses[keyof GetShopByIdResponses];

export type PostShopAddData = {
    body: {
        /**
         * 商圈ID
         */
        cbdId: string;
        /**
         * 分区ID
         */
        partId: string;
        /**
         * 铺位ID
         */
        positionId: string;
        /**
         * 类型，1-餐饮 2-轻食 3-茶楼 4-茶饮/咖啡 5-咖啡馆 6-酒店
         */
        type: string;
        /**
         * 品类标签
         */
        type_tag?: string;
        /**
         * 商业类型，1-独立自营店 2-连锁自营店 3-连锁加盟店
         */
        business_type: string;
        /**
         * 字号
         */
        trademark: string;
        /**
         * 分店
         */
        branch?: string;
        /**
         * 坐标，经纬度
         */
        location: [
            unknown,
            unknown
        ];
        /**
         * 是否认证
         */
        verified?: boolean;
        /**
         * 经营时长，1-一年内新店 2-1~2年 3-2~5年 4-五年以上
         */
        duration: string;
        /**
         * 是否展示消费数据
         */
        consume_display?: boolean;
        /**
         * 人均消费最低到最高值，单位(分)
         */
        average_expense: [
            unknown,
            unknown
        ];
        /**
         * 性别，1-不限 2-男 3-女
         */
        sex: string;
        /**
         * 年龄段最低到最高值
         */
        age: [
            unknown,
            unknown
        ];
        /**
         * 身份标签
         */
        id_tag?: string;
        /**
         * 标识图片
         */
        sign_photo?: string;
        /**
         * 认证图片
         */
        verify_photo?: Array<string>;
        /**
         * 外景图片
         */
        environment_photo?: Array<string>;
        /**
         * 内景图片
         */
        building_photo?: Array<string>;
        /**
         * 品牌营销图片
         */
        brand_photo?: Array<string>;
        /**
         * 联系人姓名
         */
        contact_name?: string;
        /**
         * 联系人电话
         */
        contact_phone?: string;
        /**
         * 联系人类型，1-老板 2-店长 3-店员 4-总店管理人员
         */
        contact_type?: string;
        /**
         * 面积，单位(平方米)
         */
        total_area?: number;
        /**
         * 客区面积
         */
        customer_area?: number;
        /**
         * 店员人数
         */
        clerk_count?: number;
        /**
         * 营业时间
         */
        business_hours: [
            unknown,
            unknown
        ];
        /**
         * 休息日，1-周一 2-周二 3-周三 4-周四 5-周五 6-周六 7-周日 8-按需
         */
        rest_days: Array<string>;
        /**
         * 客流高峰，1-早餐 2-午餐 3-晚餐 4-宵夜 5-上午 6-下午 7-晚上 8-深夜
         */
        volume_peak: Array<string>;
        /**
         * 1-春 2-夏 3-秋 4-冬 5-节假日 6-工作日 7-非工作日
         */
        season: Array<string>;
        /**
         * 店铺简介
         */
        shop_description?: string;
        /**
         * 投放简介
         */
        put_description?: string;
        /**
         * 是否开放
         */
        displayed?: boolean;
        /**
         * 价格基数（单位：分）
         */
        price_base: number;
        /**
         * 分类标签
         */
        classify_tag?: string;
        /**
         * 备注
         */
        remark?: string;
    };
    path?: never;
    query?: never;
    url: '/shop/add';
};

export type PostShopAddResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            /**
             * 新建店铺ID
             */
            id: string;
        };
    };
};

export type PostShopAddResponse = PostShopAddResponses[keyof PostShopAddResponses];

export type PostShopUpdateData = {
    body: {
        /**
         * 类型，1-餐饮 2-轻食 3-茶楼 4-茶饮/咖啡 5-咖啡馆 6-酒店
         */
        type: string;
        /**
         * 品类标签
         */
        type_tag?: string;
        /**
         * 商业类型，1-独立自营店 2-连锁自营店 3-连锁加盟店
         */
        business_type: string;
        /**
         * 字号
         */
        trademark: string;
        /**
         * 分店
         */
        branch?: string;
        /**
         * 坐标，经纬度
         */
        location: [
            unknown,
            unknown
        ];
        /**
         * 是否认证
         */
        verified?: boolean;
        /**
         * 经营时长，1-一年内新店 2-1~2年 3-2~5年 4-五年以上
         */
        duration: string;
        /**
         * 是否展示消费数据
         */
        consume_display?: boolean;
        /**
         * 人均消费最低到最高值，单位(分)
         */
        average_expense: [
            unknown,
            unknown
        ];
        /**
         * 性别，1-不限 2-男 3-女
         */
        sex: string;
        /**
         * 年龄段最低到最高值
         */
        age: [
            unknown,
            unknown
        ];
        /**
         * 身份标签
         */
        id_tag?: string;
        /**
         * 标识图片
         */
        sign_photo?: string;
        /**
         * 认证图片
         */
        verify_photo?: Array<string>;
        /**
         * 外景图片
         */
        environment_photo?: Array<string>;
        /**
         * 内景图片
         */
        building_photo?: Array<string>;
        /**
         * 品牌营销图片
         */
        brand_photo?: Array<string>;
        /**
         * 联系人姓名
         */
        contact_name?: string;
        /**
         * 联系人电话
         */
        contact_phone?: string;
        /**
         * 联系人类型，1-老板 2-店长 3-店员 4-总店管理人员
         */
        contact_type?: string;
        /**
         * 面积，单位(平方米)
         */
        total_area?: number;
        /**
         * 客区面积
         */
        customer_area?: number;
        /**
         * 店员人数
         */
        clerk_count?: number;
        /**
         * 营业时间
         */
        business_hours: [
            unknown,
            unknown
        ];
        /**
         * 休息日，1-周一 2-周二 3-周三 4-周四 5-周五 6-周六 7-周日 8-按需
         */
        rest_days: Array<string>;
        /**
         * 客流高峰，1-早餐 2-午餐 3-晚餐 4-宵夜 5-上午 6-下午 7-晚上 8-深夜
         */
        volume_peak: Array<string>;
        /**
         * 1-春 2-夏 3-秋 4-冬 5-节假日 6-工作日 7-非工作日
         */
        season: Array<string>;
        /**
         * 店铺简介
         */
        shop_description?: string;
        /**
         * 投放简介
         */
        put_description?: string;
        /**
         * 是否开放
         */
        displayed?: boolean;
        /**
         * 价格基数（单位：分）
         */
        price_base: number;
        /**
         * 分类标签
         */
        classify_tag?: string;
        /**
         * 备注
         */
        remark?: string;
        /**
         * 店铺ID
         */
        id: string;
    };
    path?: never;
    query?: never;
    url: '/shop/update';
};

export type PostShopUpdateResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: unknown;
    };
};

export type PostShopUpdateResponse = PostShopUpdateResponses[keyof PostShopUpdateResponses];

export type PostShopDeleteData = {
    body: {
        /**
         * 店铺ID
         */
        id: string;
    };
    path?: never;
    query?: never;
    url: '/shop/delete';
};

export type PostShopDeleteResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: unknown;
    };
};

export type PostShopDeleteResponse = PostShopDeleteResponses[keyof PostShopDeleteResponses];

export type PostSpaceListData = {
    body: {
        /**
         * 店铺ID
         */
        shopId: string;
    };
    path?: never;
    query?: never;
    url: '/space/list';
};

export type PostSpaceListResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            list: Array<{
                id: string;
                type: string;
                setting: {};
                count: number;
                state: string;
                photo: Array<string>;
                /**
                 * 价格因子
                 */
                priceFactor?: number;
                updatedAt: string;
            }>;
        };
    };
};

export type PostSpaceListResponse = PostSpaceListResponses[keyof PostSpaceListResponses];

export type GetSpaceByIdData = {
    body?: never;
    path: {
        /**
         * 广告位ID
         */
        id: string;
    };
    query?: never;
    url: '/space/{id}';
};

export type GetSpaceByIdResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            id: string;
            type: string;
            setting: {};
            count: number;
            state: string;
            photo: Array<string>;
            /**
             * 价格因子
             */
            priceFactor?: number;
            updatedAt: string;
        };
    };
};

export type GetSpaceByIdResponse = GetSpaceByIdResponses[keyof GetSpaceByIdResponses];

export type PostSpaceAddData = {
    body: {
        /**
         * 店铺ID
         */
        shopId: string;
        /**
         * 广告位类型，1-方桌不干胶贴 2-方桌餐垫纸 3-立牌 4-X展架 5-电视/LED屏幕 6-投影仪
         */
        type: number;
        /**
         * 广告位设置
         */
        setting: {};
        /**
         * 广告位数量
         */
        count?: number;
        /**
         * 状态 1-启用 2-禁用
         */
        state: string;
        /**
         * 价格因子
         */
        priceFactor?: number;
        /**
         * 分类标签
         */
        tag?: string;
        /**
         * 位置，1-主客区/大堂 2-店铺入口 3-入口通道 4-独立房间/包间 5-通往洗手间过道 6-洗手间 7-店铺外摆区/店外公共区 8-店外墙面(非临街) 9-店外墙面(临街)
         */
        site?: number;
        /**
         * 稳定性，1-固定 2-半固定 3-移动 4-临时
         */
        stability?: number;
        /**
         * 相册
         */
        photo?: Array<string>;
        /**
         * 投放推介
         */
        description?: string;
        /**
         * 设计注意事项
         */
        design_attention?: string;
        /**
         * 施工注意事项
         */
        construction_attention?: string;
    };
    path?: never;
    query?: never;
    url: '/space/add';
};

export type PostSpaceAddResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: unknown;
    };
};

export type PostSpaceAddResponse = PostSpaceAddResponses[keyof PostSpaceAddResponses];

export type PostSpaceUpdateData = {
    body: {
        /**
         * 广告位类型，1-方桌不干胶贴 2-方桌餐垫纸 3-立牌 4-X展架 5-电视/LED屏幕 6-投影仪
         */
        type: number;
        /**
         * 广告位设置
         */
        setting: {};
        /**
         * 广告位数量
         */
        count?: number;
        /**
         * 状态 1-启用 2-禁用
         */
        state: string;
        /**
         * 价格因子
         */
        priceFactor?: number;
        /**
         * 分类标签
         */
        tag?: string;
        /**
         * 位置，1-主客区/大堂 2-店铺入口 3-入口通道 4-独立房间/包间 5-通往洗手间过道 6-洗手间 7-店铺外摆区/店外公共区 8-店外墙面(非临街) 9-店外墙面(临街)
         */
        site?: number;
        /**
         * 稳定性，1-固定 2-半固定 3-移动 4-临时
         */
        stability?: number;
        /**
         * 相册
         */
        photo?: Array<string>;
        /**
         * 投放推介
         */
        description?: string;
        /**
         * 设计注意事项
         */
        design_attention?: string;
        /**
         * 施工注意事项
         */
        construction_attention?: string;
        /**
         * 广告位ID
         */
        id: string;
    };
    path?: never;
    query?: never;
    url: '/space/update';
};

export type PostSpaceUpdateResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: unknown;
    };
};

export type PostSpaceUpdateResponse = PostSpaceUpdateResponses[keyof PostSpaceUpdateResponses];

export type PostSpaceDeleteData = {
    body: {
        /**
         * 广告位ID
         */
        id: string;
    };
    path?: never;
    query?: never;
    url: '/space/delete';
};

export type PostSpaceDeleteResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: unknown;
    };
};

export type PostSpaceDeleteResponse = PostSpaceDeleteResponses[keyof PostSpaceDeleteResponses];

export type PostSpaceUpdateStateData = {
    body: {
        /**
         * 广告位ID
         */
        id: string;
        /**
         * 状态 1-启用 2-禁用
         */
        state: string;
    };
    path?: never;
    query?: never;
    url: '/space/updateState';
};

export type PostSpaceUpdateStateResponses = {
    /**
     * 成功响应
     */
    200: {
        code: number;
        data?: unknown;
    };
};

export type PostSpaceUpdateStateResponse = PostSpaceUpdateStateResponses[keyof PostSpaceUpdateStateResponses];

export type GetDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/';
};

export type GetDashboardResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            /**
             * 商圈总数
             */
            cbdCount: number;
            /**
             * 物业分区总数
             */
            partCount: number;
            /**
             * 铺位总数
             */
            positionCount: number;
            /**
             * 店铺总数
             */
            shopCount: number;
            /**
             * 广告位总数
             */
            spaceCount: number;
            /**
             * 广告活动总数
             */
            campaignCount: number;
        };
    };
};

export type GetDashboardResponse = GetDashboardResponses[keyof GetDashboardResponses];

export type GetDashboardRecentShopsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: string;
    };
    url: '/dashboard/recent-shops';
};

export type GetDashboardRecentShopsResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: Array<{
            id?: string;
            shop_no?: string;
            trademark?: string;
            branch?: string | null;
            type?: string;
            type_tag?: string | null;
            business_type?: string;
            verify_status?: boolean;
            cbd?: {
                id?: string;
                name?: string;
            };
            part?: {
                id?: string;
                name?: string;
            };
            createdAt?: Date;
        }>;
    };
};

export type GetDashboardRecentShopsResponse = GetDashboardRecentShopsResponses[keyof GetDashboardRecentShopsResponses];

export type GetDashboardCbdDistributionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/cbd-distribution';
};

export type GetDashboardCbdDistributionResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: Array<{
            id?: string;
            name?: string;
            district?: string;
            shopCount?: number;
            partCount?: number;
        }>;
    };
};

export type GetDashboardCbdDistributionResponse = GetDashboardCbdDistributionResponses[keyof GetDashboardCbdDistributionResponses];

export type GetDashboardShopTypeDistributionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/shop-type-distribution';
};

export type GetDashboardShopTypeDistributionResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: Array<{
            type?: string;
            count?: number;
        }>;
    };
};

export type GetDashboardShopTypeDistributionResponse = GetDashboardShopTypeDistributionResponses[keyof GetDashboardShopTypeDistributionResponses];

export type GetAuditLogData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        operationType?: string;
        targetType?: string;
        operatorId?: string;
        startDate?: string;
        endDate?: string;
        keyword?: string;
    };
    url: '/auditLog/';
};

export type GetAuditLogResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            items: Array<{
                id: string;
                operationType: string;
                targetType: string;
                targetId: string;
                targetName: string;
                content: string;
                operatorId: string;
                operatorName: string;
                operationTime: string;
                details?: {};
                ipAddress: unknown;
                userAgent: unknown;
            }>;
            total: number;
            page: number;
            pageSize: number;
            totalPages: number;
        };
    };
};

export type GetAuditLogResponse = GetAuditLogResponses[keyof GetAuditLogResponses];

export type GetAuditLogByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/auditLog/{id}';
};

export type GetAuditLogByIdResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: {
            id: string;
            operationType: string;
            targetType: string;
            targetId: string;
            targetName: string;
            content: string;
            operatorId: string;
            operatorName: string;
            operationTime: string;
            details?: {};
            ipAddress: unknown;
            userAgent: unknown;
        };
    };
};

export type GetAuditLogByIdResponse = GetAuditLogByIdResponses[keyof GetAuditLogByIdResponses];

export type GetAuditLogStatsOperationTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auditLog/stats/operation-types';
};

export type GetAuditLogStatsOperationTypesResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: Array<{
            operationType?: string;
            count?: number;
        }>;
    };
};

export type GetAuditLogStatsOperationTypesResponse = GetAuditLogStatsOperationTypesResponses[keyof GetAuditLogStatsOperationTypesResponses];

export type GetAuditLogStatsRecentActivityData = {
    body?: never;
    path?: never;
    query?: {
        days?: string;
    };
    url: '/auditLog/stats/recent-activity';
};

export type GetAuditLogStatsRecentActivityResponses = {
    /**
     * 成功响应
     */
    200: {
        code?: number;
        data?: Array<{
            date?: Date;
            count?: number;
        }>;
    };
};

export type GetAuditLogStatsRecentActivityResponse = GetAuditLogStatsRecentActivityResponses[keyof GetAuditLogStatsRecentActivityResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};