// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zCbdResponseSchema = z.object({
    id: z.string(),
    name: z.string(),
    addr: z.unknown()
});

export const zCityResponseSchema = z.object({
    id: z.string(),
    name: z.string()
});

export const zDistrictResponseSchema = z.object({
    id: z.string(),
    name: z.string()
});

export const zPartResponseSchema = z.object({
    id: z.string(),
    name: z.string(),
    sequence: z.number(),
    total_space: z.number()
});

export const zShopResponseSchema = z.object({
    shopId: z.string(),
    shop_no: z.string(),
    trademark: z.string(),
    branch: z.unknown(),
    total_space: z.number(),
    put_space: z.number(),
    price_base: z.number(),
    verified: z.boolean(),
    displayed: z.boolean(),
    type: z.number(),
    type_tag: z.unknown(),
    photo: z.array(z.string()),
    remark: z.unknown(),
    business_hours: z.array(z.number())
});

export const zSpaceResponseSchema = z.object({
    id: z.string(),
    type: z.string(),
    setting: z.object({}),
    count: z.number(),
    state: z.string(),
    photo: z.array(z.string()),
    priceFactor: z.number().optional().default(1)
});

export const zPosition = z.object({
    positionId: z.string(),
    position_no: z.string(),
    shopId: z.unknown(),
    shop_no: z.unknown(),
    total_space: z.number(),
    put_space: z.number(),
    price_base: z.number(),
    verified: z.boolean(),
    displayed: z.boolean(),
    type: z.unknown(),
    type_tag: z.unknown(),
    photo: z.array(z.string()),
    remark: z.unknown(),
    business_hours: z.array(z.number())
});

export const zAuditLog = z.object({
    id: z.string(),
    operationType: z.string(),
    targetType: z.string(),
    targetId: z.string(),
    targetName: z.string(),
    content: z.string(),
    operatorId: z.string(),
    operatorName: z.string(),
    operationTime: z.string(),
    details: z.object({}).optional(),
    ipAddress: z.unknown(),
    userAgent: z.unknown()
});

export const zGetCityCityListResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        list: z.array(z.object({
            id: z.string(),
            name: z.string()
        }))
    }).optional()
});

export const zPostDistrictListResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        list: z.array(z.object({
            id: z.string(),
            name: z.string()
        }))
    }).optional()
});

export const zPostCbdListResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        list: z.array(z.object({
            id: z.string(),
            name: z.string(),
            addr: z.unknown()
        }))
    }).optional()
});

export const zPostPartListResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        list: z.array(z.object({
            id: z.string(),
            name: z.string(),
            sequence: z.number(),
            total_space: z.number()
        }))
    }).optional()
});

export const zGetPartByIdResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        id: z.string(),
        name: z.string(),
        sequence: z.number(),
        total_space: z.number()
    }).optional()
});

export const zPostPartAddResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostPartUpdateResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostPartDeleteResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostPositionListResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        list: z.array(z.object({
            positionId: z.string(),
            position_no: z.string(),
            shopId: z.unknown(),
            shop_no: z.unknown(),
            total_space: z.number(),
            put_space: z.number(),
            price_base: z.number(),
            verified: z.boolean(),
            displayed: z.boolean(),
            type: z.unknown(),
            type_tag: z.unknown(),
            photo: z.array(z.string()),
            remark: z.unknown(),
            business_hours: z.array(z.number())
        }))
    }).optional()
});

export const zGetPositionByIdResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        positionId: z.string(),
        position_no: z.string(),
        shopId: z.unknown(),
        shop_no: z.unknown(),
        total_space: z.number(),
        put_space: z.number(),
        price_base: z.number(),
        verified: z.boolean(),
        displayed: z.boolean(),
        type: z.unknown(),
        type_tag: z.unknown(),
        photo: z.array(z.string()),
        remark: z.unknown(),
        business_hours: z.array(z.number())
    }).optional()
});

export const zPostPositionAddResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostPositionUpdateResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostPositionDeleteResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostPositionSetResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostPositionBindShopResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostPositionMarkResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zGetShopListUnbindResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        list: z.array(z.object({
            shopId: z.string(),
            shop_no: z.string(),
            trademark: z.string(),
            branch: z.unknown(),
            total_space: z.number(),
            put_space: z.number(),
            price_base: z.number(),
            verified: z.boolean(),
            displayed: z.boolean(),
            type: z.number(),
            type_tag: z.unknown(),
            photo: z.array(z.string()),
            remark: z.unknown(),
            business_hours: z.array(z.number())
        }))
    }).optional()
});

export const zPostShopAddResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        id: z.string()
    }).optional()
});

export const zPostShopUpdateResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostShopDeleteResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostSpaceListResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        list: z.array(z.object({
            id: z.string(),
            type: z.string(),
            setting: z.object({}),
            count: z.number(),
            state: z.string(),
            photo: z.array(z.string()),
            priceFactor: z.number().optional().default(1)
        }))
    }).optional()
});

export const zGetSpaceByIdResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        id: z.string(),
        type: z.string(),
        setting: z.object({}),
        count: z.number(),
        state: z.string(),
        photo: z.array(z.string()),
        priceFactor: z.number().optional().default(1)
    }).optional()
});

export const zPostSpaceAddResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostSpaceUpdateResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostSpaceDeleteResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostSpaceUpdateStateResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zGetDashboardResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        cbdCount: z.number().int().gte(0),
        partCount: z.number().int().gte(0),
        positionCount: z.number().int().gte(0),
        shopCount: z.number().int().gte(0),
        spaceCount: z.number().int().gte(0),
        campaignCount: z.number().int().gte(0)
    }).optional()
});

export const zGetDashboardRecentShopsResponse = z.object({
    code: z.number().optional(),
    data: z.array(z.object({
        id: z.string().optional(),
        shop_no: z.string().optional(),
        trademark: z.string().optional(),
        branch: z.union([
            z.string(),
            z.null()
        ]).optional(),
        type: z.string().optional(),
        type_tag: z.union([
            z.string(),
            z.null()
        ]).optional(),
        business_type: z.string().optional(),
        verify_status: z.boolean().optional(),
        cbd: z.object({
            id: z.string().optional(),
            name: z.string().optional()
        }).optional(),
        part: z.object({
            id: z.string().optional(),
            name: z.string().optional()
        }).optional(),
        createdAt: z.string().datetime().optional()
    })).optional()
});

export const zGetDashboardCbdDistributionResponse = z.object({
    code: z.number().optional(),
    data: z.array(z.object({
        id: z.string().optional(),
        name: z.string().optional(),
        district: z.string().optional(),
        shopCount: z.number().optional(),
        partCount: z.number().optional()
    })).optional()
});

export const zGetDashboardShopTypeDistributionResponse = z.object({
    code: z.number().optional(),
    data: z.array(z.object({
        type: z.string().optional(),
        count: z.number().optional()
    })).optional()
});

export const zGetAuditLogResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        items: z.array(z.object({
            id: z.string(),
            operationType: z.string(),
            targetType: z.string(),
            targetId: z.string(),
            targetName: z.string(),
            content: z.string(),
            operatorId: z.string(),
            operatorName: z.string(),
            operationTime: z.string(),
            details: z.object({}).optional(),
            ipAddress: z.unknown(),
            userAgent: z.unknown()
        })),
        total: z.number(),
        page: z.number(),
        pageSize: z.number(),
        totalPages: z.number()
    }).optional()
});

export const zGetAuditLogByIdResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        id: z.string(),
        operationType: z.string(),
        targetType: z.string(),
        targetId: z.string(),
        targetName: z.string(),
        content: z.string(),
        operatorId: z.string(),
        operatorName: z.string(),
        operationTime: z.string(),
        details: z.object({}).optional(),
        ipAddress: z.unknown(),
        userAgent: z.unknown()
    }).optional()
});

export const zGetAuditLogStatsOperationTypesResponse = z.object({
    code: z.number().optional(),
    data: z.array(z.object({
        operationType: z.string().optional(),
        count: z.number().optional()
    })).optional()
});

export const zGetAuditLogStatsRecentActivityResponse = z.object({
    code: z.number().optional(),
    data: z.array(z.object({
        date: z.string().date().optional(),
        count: z.number().optional()
    })).optional()
});