// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zCbdResponseSchema = z.object({
    id: z.string(),
    name: z.string(),
    addr: z.unknown()
});

export const zCityResponseSchema = z.object({
    id: z.string(),
    name: z.string()
});

export const zDistrictResponseSchema = z.object({
    id: z.string(),
    name: z.string()
});

export const zPartResponseSchema = z.object({
    id: z.string(),
    name: z.string(),
    sequence: z.number(),
    total_space: z.number()
});

export const zShopResponseSchema = z.object({
    shopId: z.string(),
    shop_no: z.string(),
    trademark: z.string(),
    branch: z.unknown(),
    total_space: z.number(),
    put_space: z.number(),
    price_base: z.number(),
    verified: z.boolean(),
    displayed: z.boolean(),
    type: z.number(),
    type_tag: z.unknown(),
    photo: z.array(z.string()),
    remark: z.unknown(),
    business_hours: z.array(z.number())
});

export const zSpaceResponseSchema = z.object({
    id: z.string(),
    type: z.string(),
    setting: z.object({}),
    count: z.number(),
    state: z.string(),
    photo: z.array(z.string()),
    priceFactor: z.number().optional().default(1)
});

export const zPosition = z.object({
    positionId: z.string(),
    position_no: z.string(),
    shopId: z.unknown(),
    shop_no: z.unknown(),
    total_space: z.number(),
    put_space: z.number(),
    price_base: z.number(),
    verified: z.boolean(),
    displayed: z.boolean(),
    type: z.unknown(),
    type_tag: z.unknown(),
    photo: z.array(z.string()),
    remark: z.unknown(),
    business_hours: z.array(z.number())
});

export const zGetCityCityListResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        list: z.array(z.object({
            id: z.string(),
            name: z.string()
        }))
    }).optional()
});

export const zPostDistrictListResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        list: z.array(z.object({
            id: z.string(),
            name: z.string()
        }))
    }).optional()
});

export const zPostCbdListResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        list: z.array(z.object({
            id: z.string(),
            name: z.string(),
            addr: z.unknown()
        }))
    }).optional()
});

export const zPostPartListResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        list: z.array(z.object({
            id: z.string(),
            name: z.string(),
            sequence: z.number(),
            total_space: z.number()
        }))
    }).optional()
});

export const zPostPartAddResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostPartUpdateResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostPartDeleteResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostPositionListResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        list: z.array(z.object({
            positionId: z.string(),
            position_no: z.string(),
            shopId: z.unknown(),
            shop_no: z.unknown(),
            total_space: z.number(),
            put_space: z.number(),
            price_base: z.number(),
            verified: z.boolean(),
            displayed: z.boolean(),
            type: z.unknown(),
            type_tag: z.unknown(),
            photo: z.array(z.string()),
            remark: z.unknown(),
            business_hours: z.array(z.number())
        }))
    }).optional()
});

export const zPostPositionAddResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostPositionUpdateResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostPositionDeleteResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostPositionSetResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostPositionBindShopResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostPositionMarkResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zGetShopListUnbindResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        list: z.array(z.object({
            shopId: z.string(),
            shop_no: z.string(),
            trademark: z.string(),
            branch: z.unknown(),
            total_space: z.number(),
            put_space: z.number(),
            price_base: z.number(),
            verified: z.boolean(),
            displayed: z.boolean(),
            type: z.number(),
            type_tag: z.unknown(),
            photo: z.array(z.string()),
            remark: z.unknown(),
            business_hours: z.array(z.number())
        }))
    }).optional()
});

export const zPostShopAddResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        id: z.string()
    }).optional()
});

export const zPostShopUpdateResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostShopDeleteResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostSpaceListResponse = z.object({
    code: z.number().optional(),
    data: z.object({
        list: z.array(z.object({
            id: z.string(),
            type: z.string(),
            setting: z.object({}),
            count: z.number(),
            state: z.string(),
            photo: z.array(z.string()),
            priceFactor: z.number().optional().default(1)
        }))
    }).optional()
});

export const zPostSpaceAddResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostSpaceUpdateResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostSpaceDeleteResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});

export const zPostSpaceUpdateStateResponse = z.object({
    code: z.number(),
    data: z.unknown().optional()
});