/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/city/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 获取城市列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                list: {
                                    id: string;
                                    name: string;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/district/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 获取区域列表 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 城市ID */
                        parentId: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                list: {
                                    id: string;
                                    name: string;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cbd/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 获取商圈列表 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 行政区划ID */
                        districtId: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                list: {
                                    id: string;
                                    name: string;
                                    addr: null | string;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/part/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 获取物业小区列表 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description 商圈ID */
                        cbdId?: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                list: {
                                    id: string;
                                    name: string;
                                    sequence: number;
                                    total_space: number;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/part/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 获取物业小区详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 分区ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                id: string;
                                name: string;
                                sequence: number;
                                total_space: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/part/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 新增分区 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 商圈ID */
                        cbdId: string;
                        /** @description 分区名称 */
                        name: string;
                        /** @description 排序值 */
                        sequence: number;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/part/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 编辑分区 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 分区ID */
                        id: string;
                        /** @description 分区名称 */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/part/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 删除分区 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 分区ID */
                        id: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/position/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 获取铺位列表 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description 分区ID */
                        partId?: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                list: {
                                    id: string;
                                    position_no: string;
                                    shopId: null | string;
                                    shop_no: null | string;
                                    total_space: number;
                                    put_space: number;
                                    price_base: number;
                                    verified: boolean;
                                    displayed: boolean;
                                    type: null | string;
                                    type_tag: null | string;
                                    photo: string[];
                                    remark: null | string;
                                    business_hours: number[];
                                }[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/position/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 获取铺位详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 铺位ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功响应 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                positionId: string;
                                position_no: string;
                                shopId: null | string;
                                shop_no: null | string;
                                total_space: number;
                                put_space: number;
                                price_base: number;
                                verified: boolean;
                                displayed: boolean;
                                type: null | string;
                                type_tag: null | string;
                                photo: string[];
                                remark: null | string;
                                business_hours: number[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/position/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 新增铺位 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 商圈ID */
                        cbdId: string;
                        /** @description 分区ID */
                        partId: string;
                        /** @description 铺位编号 */
                        no: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/position/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 编辑铺位 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 铺位ID */
                        id: string;
                        /** @description 铺位编号 */
                        no: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/position/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 删除铺位 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 铺位ID */
                        id: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/position/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 置为空铺 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 铺位ID */
                        id: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/position/bindShop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 关联新商家 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 铺位ID */
                        id: string;
                        /** @description 商家ID */
                        shopId: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/position/mark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 快速标记铺位 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 铺位ID */
                        id: string;
                        /** @description 标记内容 */
                        remark: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 商家列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                list: {
                                    shopId: string;
                                    shop_no?: string;
                                    trademark: string;
                                    branch: null | string;
                                    total_space: number;
                                    put_space: number;
                                    price_base: number;
                                    verified: boolean;
                                    displayed: boolean;
                                    type: string;
                                    type_tag: null | string;
                                    photo: string[];
                                    remark: null | string;
                                    business_hours: number[];
                                    total_area: null | number;
                                    customer_area: null | number;
                                    clerk_count: null | number;
                                    business_type: string;
                                    duration: string;
                                    sex: string;
                                    age: number[];
                                    id_tag: null | string;
                                    sign_photo: null | string;
                                    contact_type: string;
                                    /** @description 商家简介 */
                                    shop_description?: string;
                                    /** @description 投放简介 */
                                    put_description?: string;
                                    /** @description 分类标签 */
                                    classify_tag?: string;
                                    positionId?: string;
                                    position_no?: string;
                                    /** @description 休息日，1-周一 2-周二 3-周三 4-周四 5-周五 6-周六 7-周日 8-按需 */
                                    rest_days: string[];
                                    /** @description 客流高峰，1-早餐 2-午餐 3-晚餐 4-宵夜 5-上午 6-下午 7-晚上 8-深夜 */
                                    volume_peak: string[];
                                    /** @description 1-春 2-夏 3-秋 4-冬 5-节假日 6-工作日 7-非工作日 */
                                    season: string[];
                                }[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/listUnbind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 获取未关联商家列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                list: {
                                    shopId: string;
                                    shop_no?: string;
                                    trademark: string;
                                    branch: null | string;
                                    total_space: number;
                                    put_space: number;
                                    price_base: number;
                                    verified: boolean;
                                    displayed: boolean;
                                    type: string;
                                    type_tag: null | string;
                                    photo: string[];
                                    remark: null | string;
                                    business_hours: number[];
                                    total_area: null | number;
                                    customer_area: null | number;
                                    clerk_count: null | number;
                                    business_type: string;
                                    duration: string;
                                    sex: string;
                                    age: number[];
                                    id_tag: null | string;
                                    sign_photo: null | string;
                                    contact_type: string;
                                    /** @description 商家简介 */
                                    shop_description?: string;
                                    /** @description 投放简介 */
                                    put_description?: string;
                                    /** @description 分类标签 */
                                    classify_tag?: string;
                                    positionId?: string;
                                    position_no?: string;
                                    /** @description 休息日，1-周一 2-周二 3-周三 4-周四 5-周五 6-周六 7-周日 8-按需 */
                                    rest_days: string[];
                                    /** @description 客流高峰，1-早餐 2-午餐 3-晚餐 4-宵夜 5-上午 6-下午 7-晚上 8-深夜 */
                                    volume_peak: string[];
                                    /** @description 1-春 2-夏 3-秋 4-冬 5-节假日 6-工作日 7-非工作日 */
                                    season: string[];
                                }[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 商家详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 商家ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                shopId: string;
                                shop_no?: string;
                                trademark: string;
                                branch: null | string;
                                total_space: number;
                                put_space: number;
                                price_base: number;
                                verified: boolean;
                                displayed: boolean;
                                type: string;
                                type_tag: null | string;
                                photo: string[];
                                remark: null | string;
                                business_hours: number[];
                                total_area: null | number;
                                customer_area: null | number;
                                clerk_count: null | number;
                                business_type: string;
                                duration: string;
                                sex: string;
                                age: number[];
                                id_tag: null | string;
                                sign_photo: null | string;
                                contact_type: string;
                                /** @description 商家简介 */
                                shop_description?: string;
                                /** @description 投放简介 */
                                put_description?: string;
                                /** @description 分类标签 */
                                classify_tag?: string;
                                positionId?: string;
                                position_no?: string;
                                /** @description 休息日，1-周一 2-周二 3-周三 4-周四 5-周五 6-周六 7-周日 8-按需 */
                                rest_days: string[];
                                /** @description 客流高峰，1-早餐 2-午餐 3-晚餐 4-宵夜 5-上午 6-下午 7-晚上 8-深夜 */
                                volume_peak: string[];
                                /** @description 1-春 2-夏 3-秋 4-冬 5-节假日 6-工作日 7-非工作日 */
                                season: string[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 新建商家 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 商圈ID */
                        cbdId: string;
                        /** @description 分区ID */
                        partId: string;
                        /** @description 铺位ID */
                        positionId?: string;
                        /** @description 类型，1-餐饮 2-轻食 3-茶楼 4-茶饮/咖啡 5-咖啡馆 6-酒店 */
                        type: string;
                        /** @description 品类标签 */
                        type_tag?: string;
                        /** @description 商业类型，1-独立自营店 2-连锁自营店 3-连锁加盟店 */
                        business_type: string;
                        /** @description 字号 */
                        trademark: string;
                        /** @description 分店 */
                        branch?: string;
                        /** @description 坐标，经纬度 */
                        location: [
                            number,
                            number
                        ];
                        /**
                         * @description 是否认证
                         * @default false
                         */
                        verified?: boolean;
                        /** @description 经营时长，1-一年内新店 2-1~2年 3-2~5年 4-五年以上 */
                        duration: string;
                        /**
                         * @description 是否展示消费数据
                         * @default true
                         */
                        consume_display?: boolean;
                        /** @description 人均消费最低到最高值，单位(分) */
                        average_expense: [
                            number,
                            number
                        ];
                        /** @description 性别，1-不限 2-男 3-女 */
                        sex: string;
                        /** @description 年龄段最低到最高值 */
                        age: [
                            number,
                            number
                        ];
                        /** @description 身份标签 */
                        id_tag?: string;
                        /** @description 标识图片 */
                        sign_photo?: string;
                        /** @description 认证图片 */
                        verify_photo?: string[];
                        /** @description 外景图片 */
                        environment_photo?: string[];
                        /** @description 内景图片 */
                        building_photo?: string[];
                        /** @description 品牌营销图片 */
                        brand_photo?: string[];
                        /** @description 联系人姓名 */
                        contact_name?: string;
                        /** @description 联系人电话 */
                        contact_phone?: string;
                        /** @description 联系人类型，1-老板 2-店长 3-店员 4-总店管理人员 */
                        contact_type?: string;
                        /** @description 面积，单位(平方米) */
                        total_area?: number;
                        /** @description 客区面积 */
                        customer_area?: number;
                        /** @description 店员人数 */
                        clerk_count?: number;
                        /** @description 营业时间 */
                        business_hours: [
                            number,
                            number
                        ];
                        /** @description 休息日，1-周一 2-周二 3-周三 4-周四 5-周五 6-周六 7-周日 8-按需 */
                        rest_days: string[];
                        /** @description 客流高峰，1-早餐 2-午餐 3-晚餐 4-宵夜 5-上午 6-下午 7-晚上 8-深夜 */
                        volume_peak: string[];
                        /** @description 1-春 2-夏 3-秋 4-冬 5-节假日 6-工作日 7-非工作日 */
                        season: string[];
                        /** @description 商家简介 */
                        shop_description?: string;
                        /** @description 投放简介 */
                        put_description?: string;
                        /**
                         * @description 是否开放
                         * @default true
                         */
                        displayed?: boolean;
                        /** @description 价格基数（单位：分） */
                        price_base: number;
                        /** @description 分类标签 */
                        classify_tag?: string;
                        /** @description 备注 */
                        remark?: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                /** @description 新建商家ID */
                                id: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 编辑商家 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 类型，1-餐饮 2-轻食 3-茶楼 4-茶饮/咖啡 5-咖啡馆 6-酒店 */
                        type: string;
                        /** @description 品类标签 */
                        type_tag?: string;
                        /** @description 商业类型，1-独立自营店 2-连锁自营店 3-连锁加盟店 */
                        business_type: string;
                        /** @description 字号 */
                        trademark: string;
                        /** @description 分店 */
                        branch?: string;
                        /** @description 坐标，经纬度 */
                        location: [
                            number,
                            number
                        ];
                        /**
                         * @description 是否认证
                         * @default false
                         */
                        verified?: boolean;
                        /** @description 经营时长，1-一年内新店 2-1~2年 3-2~5年 4-五年以上 */
                        duration: string;
                        /**
                         * @description 是否展示消费数据
                         * @default true
                         */
                        consume_display?: boolean;
                        /** @description 人均消费最低到最高值，单位(分) */
                        average_expense: [
                            number,
                            number
                        ];
                        /** @description 性别，1-不限 2-男 3-女 */
                        sex: string;
                        /** @description 年龄段最低到最高值 */
                        age: [
                            number,
                            number
                        ];
                        /** @description 身份标签 */
                        id_tag?: string;
                        /** @description 标识图片 */
                        sign_photo?: string;
                        /** @description 认证图片 */
                        verify_photo?: string[];
                        /** @description 外景图片 */
                        environment_photo?: string[];
                        /** @description 内景图片 */
                        building_photo?: string[];
                        /** @description 品牌营销图片 */
                        brand_photo?: string[];
                        /** @description 联系人姓名 */
                        contact_name?: string;
                        /** @description 联系人电话 */
                        contact_phone?: string;
                        /** @description 联系人类型，1-老板 2-店长 3-店员 4-总店管理人员 */
                        contact_type?: string;
                        /** @description 面积，单位(平方米) */
                        total_area?: number;
                        /** @description 客区面积 */
                        customer_area?: number;
                        /** @description 店员人数 */
                        clerk_count?: number;
                        /** @description 营业时间 */
                        business_hours: [
                            number,
                            number
                        ];
                        /** @description 休息日，1-周一 2-周二 3-周三 4-周四 5-周五 6-周六 7-周日 8-按需 */
                        rest_days: string[];
                        /** @description 客流高峰，1-早餐 2-午餐 3-晚餐 4-宵夜 5-上午 6-下午 7-晚上 8-深夜 */
                        volume_peak: string[];
                        /** @description 1-春 2-夏 3-秋 4-冬 5-节假日 6-工作日 7-非工作日 */
                        season: string[];
                        /** @description 商家简介 */
                        shop_description?: string;
                        /** @description 投放简介 */
                        put_description?: string;
                        /**
                         * @description 是否开放
                         * @default true
                         */
                        displayed?: boolean;
                        /** @description 价格基数（单位：分） */
                        price_base: number;
                        /** @description 分类标签 */
                        classify_tag?: string;
                        /** @description 备注 */
                        remark?: string;
                        /** @description 商家ID */
                        id: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 删除商家 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 商家ID */
                        id: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/space/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 获取广告位列表 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 商家ID */
                        shopId: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                list: {
                                    id: string;
                                    type: string;
                                    setting: {
                                        [key: string]: unknown;
                                    };
                                    count: number;
                                    state: string;
                                    /**
                                     * @description 价格因子
                                     * @default 1
                                     */
                                    price_factor: number;
                                    updatedAt: string;
                                    shopId: string;
                                    shop?: {
                                        /** @description 商标 */
                                        trademark?: string;
                                        /** @description 门店号 */
                                        shop_no?: string;
                                        /** @description 分店 */
                                        branch?: string;
                                        /** @description 品类标签 */
                                        type_tag?: string;
                                    };
                                    /** @description 分类标签 */
                                    tag?: string;
                                    /** @description 位置，1-主客区/大堂 2-商家入口 3-入口通道 4-独立房间/包间 5-通往洗手间过道 6-洗手间 7-商家外摆区/店外公共区 8-店外墙面(非临街) 9-店外墙面(临街) */
                                    site?: string;
                                    /** @description 稳定性，1-固定 2-半固定 3-移动 4-临时 */
                                    stability?: string;
                                    /** @description 相册 */
                                    photo?: string[];
                                    /** @description 投放推介 */
                                    description?: string;
                                    /** @description 设计注意事项 */
                                    design_attention?: string;
                                    /** @description 施工注意事项 */
                                    construction_attention?: string;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/space/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 获取广告位详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 广告位ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                id: string;
                                type: string;
                                setting: {
                                    [key: string]: unknown;
                                };
                                count: number;
                                state: string;
                                /**
                                 * @description 价格因子
                                 * @default 1
                                 */
                                price_factor: number;
                                updatedAt: string;
                                shopId: string;
                                shop?: {
                                    /** @description 商标 */
                                    trademark?: string;
                                    /** @description 门店号 */
                                    shop_no?: string;
                                    /** @description 分店 */
                                    branch?: string;
                                    /** @description 品类标签 */
                                    type_tag?: string;
                                };
                                /** @description 分类标签 */
                                tag?: string;
                                /** @description 位置，1-主客区/大堂 2-商家入口 3-入口通道 4-独立房间/包间 5-通往洗手间过道 6-洗手间 7-商家外摆区/店外公共区 8-店外墙面(非临街) 9-店外墙面(临街) */
                                site?: string;
                                /** @description 稳定性，1-固定 2-半固定 3-移动 4-临时 */
                                stability?: string;
                                /** @description 相册 */
                                photo?: string[];
                                /** @description 投放推介 */
                                description?: string;
                                /** @description 设计注意事项 */
                                design_attention?: string;
                                /** @description 施工注意事项 */
                                construction_attention?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/space/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 新建广告位 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 商家ID */
                        shopId: string;
                        /** @description 广告位类型，1-方桌不干胶贴 2-方桌餐垫纸 3-立牌 4-X展架 5-电视/LED屏幕 6-投影仪 */
                        type: string;
                        /** @description 广告位设置 */
                        setting: {
                            [key: string]: unknown;
                        };
                        /**
                         * @description 广告位数量
                         * @default 1
                         */
                        count?: number;
                        /** @description 状态 1-启用 2-禁用 */
                        state: string;
                        /**
                         * @description 价格因子
                         * @default 1
                         */
                        price_factor?: number;
                        /** @description 分类标签 */
                        tag?: string;
                        /** @description 位置，1-主客区/大堂 2-商家入口 3-入口通道 4-独立房间/包间 5-通往洗手间过道 6-洗手间 7-商家外摆区/店外公共区 8-店外墙面(非临街) 9-店外墙面(临街) */
                        site?: string;
                        /** @description 稳定性，1-固定 2-半固定 3-移动 4-临时 */
                        stability?: string;
                        /** @description 相册 */
                        photo?: string[];
                        /** @description 投放推介 */
                        description?: string;
                        /** @description 设计注意事项 */
                        design_attention?: string;
                        /** @description 施工注意事项 */
                        construction_attention?: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/space/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 编辑广告位 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 广告位类型，1-方桌不干胶贴 2-方桌餐垫纸 3-立牌 4-X展架 5-电视/LED屏幕 6-投影仪 */
                        type: string;
                        /** @description 广告位设置 */
                        setting: {
                            [key: string]: unknown;
                        };
                        /**
                         * @description 广告位数量
                         * @default 1
                         */
                        count?: number;
                        /** @description 状态 1-启用 2-禁用 */
                        state: string;
                        /**
                         * @description 价格因子
                         * @default 1
                         */
                        price_factor?: number;
                        /** @description 分类标签 */
                        tag?: string;
                        /** @description 位置，1-主客区/大堂 2-商家入口 3-入口通道 4-独立房间/包间 5-通往洗手间过道 6-洗手间 7-商家外摆区/店外公共区 8-店外墙面(非临街) 9-店外墙面(临街) */
                        site?: string;
                        /** @description 稳定性，1-固定 2-半固定 3-移动 4-临时 */
                        stability?: string;
                        /** @description 相册 */
                        photo?: string[];
                        /** @description 投放推介 */
                        description?: string;
                        /** @description 设计注意事项 */
                        design_attention?: string;
                        /** @description 施工注意事项 */
                        construction_attention?: string;
                        /** @description 广告位ID */
                        id: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/space/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 删除广告位 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 广告位ID */
                        id: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/space/updateState": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 启用/禁用广告位 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 广告位ID */
                        id: string;
                        /** @description 状态 1-启用 2-禁用 */
                        state: string;
                    };
                };
            };
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: number;
                            data?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 获取仪表盘统计数据 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                /** @description 商圈总数 */
                                cbdCount: number;
                                /** @description 物业小区总数 */
                                partCount: number;
                                /** @description 铺位总数 */
                                positionCount: number;
                                /** @description 商家总数 */
                                shopCount: number;
                                /** @description 广告位总数 */
                                spaceCount: number;
                                /** @description 广告活动总数 */
                                campaignCount: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/recent-shops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 获取最近添加的商家 */
        get: {
            parameters: {
                query?: {
                    limit?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                id?: string;
                                shop_no?: string;
                                trademark?: string;
                                branch?: string | null;
                                type?: string;
                                type_tag?: string | null;
                                business_type?: string;
                                verify_status?: boolean;
                                cbd?: {
                                    id?: string;
                                    name?: string;
                                };
                                part?: {
                                    id?: string;
                                    name?: string;
                                };
                                /** Format: date-time */
                                createdAt?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/cbd-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 获取商圈分布统计 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                id?: string;
                                name?: string;
                                district?: string;
                                shopCount?: number;
                                partCount?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/shop-type-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 获取商家类型分布 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                type?: string;
                                count?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auditLog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 获取审计日志列表 */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                    operationType?: string;
                    targetType?: string;
                    operatorId?: string;
                    startDate?: string;
                    endDate?: string;
                    keyword?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                list: {
                                    id: string;
                                    operationType: string;
                                    targetType: string;
                                    targetId: string;
                                    targetName: string;
                                    content: string;
                                    operatorId: string;
                                    operatorName: string;
                                    operationTime: string;
                                    details?: {
                                        [key: string]: unknown;
                                    };
                                    ipAddress: null | string;
                                    userAgent: null | string;
                                }[];
                                total: number;
                                page: number;
                                pageSize: number;
                                totalPages: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auditLog/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 获取审计日志详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                id: string;
                                operationType: string;
                                targetType: string;
                                targetId: string;
                                targetName: string;
                                content: string;
                                operatorId: string;
                                operatorName: string;
                                operationTime: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                                ipAddress: null | string;
                                userAgent: null | string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auditLog/stats/operation-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 获取操作类型统计 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                operationType?: string;
                                count?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auditLog/stats/recent-activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 获取近期操作记录统计 */
        get: {
            parameters: {
                query?: {
                    days?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            data?: {
                                /** Format: date */
                                date?: string;
                                count?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** cbdResponseSchema */
        cbdResponseSchema: {
            id: string;
            name: string;
            addr: string | null;
        };
        /** cityResponseSchema */
        cityResponseSchema: {
            id: string;
            name: string;
        };
        /** districtResponseSchema */
        districtResponseSchema: {
            id: string;
            name: string;
        };
        /** partResponseSchema */
        partResponseSchema: {
            id: string;
            name: string;
            sequence: number;
            total_space: number;
        };
        /** shopResponseSchema */
        shopResponseSchema: {
            shopId: string;
            shop_no?: string;
            trademark: string;
            branch: string | null;
            total_space: number;
            put_space: number;
            price_base: number;
            verified: boolean;
            displayed: boolean;
            type: string;
            type_tag: string | null;
            photo: string[];
            remark: string | null;
            business_hours: number[];
            total_area: number | null;
            customer_area: number | null;
            clerk_count: number | null;
            business_type: string;
            duration: string;
            sex: string;
            age: number[];
            id_tag: string | null;
            sign_photo: string | null;
            contact_type: string;
            /** @description 商家简介 */
            shop_description?: string;
            /** @description 投放简介 */
            put_description?: string;
            /** @description 分类标签 */
            classify_tag?: string;
            positionId?: string;
            position_no?: string;
            /** @description 休息日，1-周一 2-周二 3-周三 4-周四 5-周五 6-周六 7-周日 8-按需 */
            rest_days: string[];
            /** @description 客流高峰，1-早餐 2-午餐 3-晚餐 4-宵夜 5-上午 6-下午 7-晚上 8-深夜 */
            volume_peak: string[];
            /** @description 1-春 2-夏 3-秋 4-冬 5-节假日 6-工作日 7-非工作日 */
            season: string[];
        };
        /** spaceResponseSchema */
        spaceResponseSchema: {
            id: string;
            type: string;
            setting: {
                [key: string]: unknown;
            };
            count: number;
            state: string;
            /**
             * @description 价格因子
             * @default 1
             */
            price_factor: number;
            updatedAt: string;
            shopId: string;
            shop?: {
                /** @description 商标 */
                trademark?: string;
                /** @description 门店号 */
                shop_no?: string;
                /** @description 分店 */
                branch?: string;
                /** @description 品类标签 */
                type_tag?: string;
            };
            /** @description 分类标签 */
            tag?: string;
            /** @description 位置，1-主客区/大堂 2-商家入口 3-入口通道 4-独立房间/包间 5-通往洗手间过道 6-洗手间 7-商家外摆区/店外公共区 8-店外墙面(非临街) 9-店外墙面(临街) */
            site?: string;
            /** @description 稳定性，1-固定 2-半固定 3-移动 4-临时 */
            stability?: string;
            /** @description 相册 */
            photo?: string[];
            /** @description 投放推介 */
            description?: string;
            /** @description 设计注意事项 */
            design_attention?: string;
            /** @description 施工注意事项 */
            construction_attention?: string;
        };
        /** Position */
        Position: {
            positionId: string;
            position_no: string;
            shopId: string | null;
            shop_no: string | null;
            total_space: number;
            put_space: number;
            price_base: number;
            verified: boolean;
            displayed: boolean;
            type: string | null;
            type_tag: string | null;
            photo: string[];
            remark: string | null;
            business_hours: number[];
        };
        /** AuditLog */
        AuditLog: {
            id: string;
            operationType: string;
            targetType: string;
            targetId: string;
            targetName: string;
            content: string;
            operatorId: string;
            operatorName: string;
            operationTime: string;
            details?: {
                [key: string]: unknown;
            };
            ipAddress: string | null;
            userAgent: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathlist: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
